/* questions_exam.js — Exam Preparation banks (drill mode, no monsters). */
(function () {
  "use strict";

  // Category codes:
  //   S = subject pronoun expected  (he, she, it, we, they, I, you)
  //   O = object pronoun expected   (him, her, us, them, me, you/it as object)
  //   C = sentence-choice — pick the whole grammatically correct sentence

  const y3s2_pronouns = [
    { q: "Adam is my brother. ___ is eight years old.", options: ["She", "He", "It", "They"], answer: 1, cat: "S" },
    { q: "Sarah is reading a book. ___ likes stories.", options: ["He", "She", "They", "It"], answer: 1, cat: "S" },
    { q: "The dog is sleeping. ___ is tired.", options: ["It", "We", "They", "Us"], answer: 0, cat: "S" },
    { q: "Ben and Tom are playing football. ___ are in the garden.", options: ["He", "It", "They", "She"], answer: 2, cat: "S" },
    { q: "Mia and I are classmates. ___ sit together.", options: ["They", "We", "Us", "She"], answer: 1, cat: "S" },
    { q: "Mum called Jake. She asked ___ to come home.", options: ["he", "him", "they", "we"], answer: 1, cat: "O" },
    { q: "I saw Anna at school. I waved to ___.", options: ["she", "her", "he", "they"], answer: 1, cat: "O" },
    { q: "The teacher gave Sam and me some books. She gave ___ three books.", options: ["we", "us", "they", "them"], answer: 1, cat: "O" },
    { q: "The boys were noisy. The teacher told ___ to be quiet.", options: ["they", "them", "he", "we"], answer: 1, cat: "O" },
    { q: "My father is a doctor. ___ works at a hospital.", options: ["He", "Him", "She", "It"], answer: 0, cat: "S" },
    { q: "Lucy is my cousin. I play with ___ every weekend.", options: ["she", "her", "they", "we"], answer: 1, cat: "O" },
    { q: "The children are hungry. ___ want some food.", options: ["Them", "They", "Him", "Us"], answer: 1, cat: "S" },
    { q: "My brother and I cleaned the room. Mum thanked ___.", options: ["we", "us", "they", "he"], answer: 1, cat: "O" },
    { q: "The cat is under the table. ___ is hiding.", options: ["It", "Them", "We", "Us"], answer: 0, cat: "S" },
    { q: "Mr Tan teaches English. ___ is very kind.", options: ["Her", "Them", "He", "Him"], answer: 2, cat: "S" },
    { q: "Kelly and Jane are sisters. ___ share a bedroom.", options: ["She", "Them", "They", "We"], answer: 2, cat: "S" },
    { q: "I am thirsty. Please give ___ some water.", options: ["I", "me", "we", "they"], answer: 1, cat: "O" },
    { q: "Dad bought a new bicycle. ___ is blue.", options: ["He", "It", "They", "Him"], answer: 1, cat: "S" },
    { q: "The teacher asked Amy a question. ___ answered correctly.", options: ["She", "Her", "Him", "Them"], answer: 0, cat: "S" },
    { q: "My friends invited ___ to their birthday party.", options: ["I", "me", "we", "they"], answer: 1, cat: "O" },
    { q: "Jack is very funny. ___ always makes us laugh.", options: ["He", "Him", "Her", "Them"], answer: 0, cat: "S" },
    { q: "I gave the book to Mary. I gave it to ___.", options: ["she", "her", "they", "we"], answer: 1, cat: "O" },
    { q: "The teacher called my friends. She asked ___ to come inside.", options: ["they", "them", "we", "he"], answer: 1, cat: "O" },
    { q: "My sister and I are hungry. ___ want to eat now.", options: ["Us", "We", "Them", "Her"], answer: 1, cat: "S" },
    { q: "The rabbit has long ears. ___ can jump very high.", options: ["They", "It", "We", "Them"], answer: 1, cat: "S" },
    { q: "Dad asked my brother to help. Dad called ___.", options: ["he", "him", "she", "they"], answer: 1, cat: "O" },
    { q: "Amy and Sue are at school. ___ are in Year 3.", options: ["They", "Them", "Her", "Us"], answer: 0, cat: "S" },
    { q: "I cannot carry this bag. Can you help ___?", options: ["I", "me", "we", "he"], answer: 1, cat: "O" },
    { q: "My grandparents are visiting us. ___ arrived this morning.", options: ["He", "Her", "They", "It"], answer: 2, cat: "S" },
    { q: "The teacher spoke to Ben and me. She spoke to ___.", options: ["we", "us", "they", "he"], answer: 1, cat: "O" }
,
    { q: "Jack likes swimming. ___ goes swimming every Saturday.", options: ["She", "Him", "He", "They"], answer: 2, cat: "S" },
    { q: "My sister is tired. ___ wants to sleep.", options: ["He", "She", "Her", "It"], answer: 1, cat: "S" },
    { q: "The bird is in the tree. ___ is singing.", options: ["It", "He", "She", "They"], answer: 0, cat: "S" },
    { q: "Sam and Joe are hungry. ___ want lunch.", options: ["Them", "We", "He", "They"], answer: 3, cat: "S" },
    { q: "Lily and I are going to the park. ___ will play on the swings.", options: ["We", "Us", "They", "I"], answer: 0, cat: "S" },
    { q: "Dad gave the ball to Tom. Dad gave it to ___.", options: ["he", "him", "her", "them"], answer: 1, cat: "O" },
    { q: "I saw Emily yesterday. I spoke to ___.", options: ["she", "her", "him", "them"], answer: 1, cat: "O" },
    { q: "Mum took my brother and me shopping. She took ___ to the mall.", options: ["we", "them", "us", "him"], answer: 2, cat: "O" },
    { q: "The puppies were hungry, so I fed ___.", options: ["them", "they", "us", "him"], answer: 0, cat: "O" },
    { q: "Please listen to ___. I have something to tell you.", options: ["I", "we", "me", "him"], answer: 2, cat: "O" },
    { q: "Peter is my best friend. ___ lives next door.", options: ["He", "She", "Him", "They"], answer: 0, cat: "S" },
    { q: "Jenny is good at drawing. ___ draws beautiful pictures.", options: ["She", "He", "Her", "It"], answer: 0, cat: "S" },
    { q: "The rabbit is white. ___ has long ears.", options: ["He", "She", "They", "It"], answer: 3, cat: "S" },
    { q: "Ali and Ravi are playing chess. ___ are having fun.", options: ["They", "Them", "We", "He"], answer: 0, cat: "S" },
    { q: "My brother and I are ready. ___ can leave now.", options: ["Us", "They", "I", "We"], answer: 3, cat: "S" },
    { q: "The teacher called Hannah. She wanted to speak to ___.", options: ["she", "her", "him", "them"], answer: 1, cat: "O" },
    { q: "Mum asked Dad to help. She called ___.", options: ["he", "her", "them", "him"], answer: 3, cat: "O" },
    { q: "The teacher gave my friends and me homework. She gave ___ five questions.", options: ["we", "us", "them", "him"], answer: 1, cat: "O" },
    { q: "I saw the children in the playground. I waved to ___.", options: ["them", "they", "us", "him"], answer: 0, cat: "O" },
    { q: "Can ___ help me carry this box?", options: ["him", "you", "her", "us"], answer: 1, cat: "S" },
    { q: "Daniel is my cousin. ___ lives in Kuala Lumpur.", options: ["He", "She", "Him", "They"], answer: 0, cat: "S" },
    { q: "My mother loves flowers. ___ has many plants in the garden.", options: ["She", "He", "Her", "It"], answer: 0, cat: "S" },
    { q: "The ball rolled under the chair. I picked ___ up.", options: ["it", "them", "him", "her"], answer: 0, cat: "O" },
    { q: "Sarah and Jane are dancing. ___ love music.", options: ["Them", "We", "He", "They"], answer: 3, cat: "S" },
    { q: "My father and I went fishing. ___ caught three fish.", options: ["Us", "They", "I", "We"], answer: 3, cat: "S" },
    { q: "Ben dropped his pencil. I picked it up for ___.", options: ["him", "he", "her", "them"], answer: 0, cat: "O" },
    { q: "Amy forgot her lunch. I shared my food with ___.", options: ["she", "her", "him", "them"], answer: 1, cat: "O" },
    { q: "Dad took my sister and me to the zoo. He bought ___ some ice cream.", options: ["we", "them", "us", "him"], answer: 2, cat: "O" },
    { q: "The kittens looked hungry. Mum gave ___ some milk.", options: ["they", "us", "him", "them"], answer: 3, cat: "O" },
    { q: "This present is for ___. Happy birthday!", options: ["him", "her", "you", "us"], answer: 2, cat: "O" }
,
    { q: "Which sentence is correct?", options: ["Him is my brother.", "He is my brother.", "Her is my brother.", "Them is my brother."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["She likes reading.", "Her likes reading.", "Him likes reading.", "Them likes reading."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["It is sleeping.", "Them is sleeping.", "Us is sleeping.", "Him are sleeping."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Them are playing football.", "They are playing football.", "Him are playing football.", "Us is playing football."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["We are classmates.", "Us are classmates.", "Them is classmates.", "Me are classmates."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mum gave the present to he.", "Mum gave the present to him.", "Mum gave the present to they.", "Mum gave the present to we."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["I spoke to she.", "I spoke to her.", "I spoke to he.", "I spoke to they."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Dad took we to school.", "Dad took us to school.", "Dad took they to school.", "Dad took he to school."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["The teacher praised they.", "The teacher praised them.", "The teacher praised we.", "The teacher praised he."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Me am hungry.", "I am hungry.", "Him am hungry.", "Them am hungry."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["She gave me a book.", "Her gave I a book.", "Him gave me a book.", "Them gave I a book."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["They helped us.", "Them helped we.", "Us helped they.", "Him helped we."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["We saw them at the park.", "Us saw they at the park.", "Them saw we at the park.", "Him saw us at the park."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["He gave her the pencil.", "Him gave she the pencil.", "Her gave he the pencil.", "Them gave she the pencil."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["They invited us to the party.", "Them invited we to the party.", "Us invited they to the party.", "Him invited we to the party."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Her is my sister.", "She is my sister.", "Him is my sister.", "Them is my sister."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["The teacher gave they some homework.", "The teacher gave them some homework.", "The teacher gave he some homework.", "The teacher gave we some homework."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Him plays football every Sunday.", "He plays football every Sunday.", "Them plays football every Sunday.", "Her play football every Sunday."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mum cooked dinner for we.", "Mum cooked dinner for us.", "Mum cooked dinner for they.", "Mum cooked dinner for he."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["They gave me a present.", "Them gave I a present.", "Us gave me a present.", "Him gave I a present."], answer: 0, cat: "C" }
  ];

  window.QUESTIONS_EXAM = { y3s2_pronouns };
})();