/* questions.js — Year 3 international English question bank.
   Built from the exam papers in /Materials and expanded with many
   extra variations so questions never repeat inside a single battle.
   Shape: { q, options:[...], answer:index, passage?:string } */
(function () {
  "use strict";

  /* ---- helpers to generate lots of non-repeating identify questions ---- */
  function shuffle(a) { a = a.slice(); for (let i = a.length - 1; i > 0; i--) { const j = (Math.random() * (i + 1)) | 0;[a[i], a[j]] = [a[j], a[i]]; } return a; }
  function pick(arr, n) { return shuffle(arr).slice(0, n); }

  // word pools (Year-3 friendly, drawn from the test papers' vocabulary)
  const NOUNS = ["school", "flower", "gate", "cow", "road", "lunch", "uniform", "pen", "book", "kitten", "ball", "park", "bush", "bicycle", "cousin", "pyramid", "teacher", "monkey", "river", "garden", "castle", "letter", "phone", "forest", "dragon", "candle", "mirror", "ghost"];
  const ADJS = ["selfish", "busy", "enormous", "loud", "wild", "broken", "yellow", "soft", "spiky", "beautiful", "sharp", "bright", "rough", "frightened", "kind", "happy", "scary", "dark", "tall", "cold", "hungry", "brave", "shiny", "rotten"];
  const VERBS = ["danced", "gathered", "climbed", "turned", "runs", "walks", "rang", "echoed", "eats", "chews", "jumps", "sings", "reads", "cooks", "plays", "hides", "kicked", "rolled", "carried", "whispered", "screamed", "crawls"];

  function identify(kind, pool, distractPools, count) {
    const out = [];
    const used = new Set();
    for (let i = 0; i < count; i++) {
      let w = pool[(Math.random() * pool.length) | 0], tries = 0;
      while (used.has(w) && tries++ < 30) w = pool[(Math.random() * pool.length) | 0];
      used.add(w);
      const others = pick([].concat(...distractPools).filter(x => x !== w), 3);
      const opts = shuffle([w, ...others]);
      out.push({ q: `Which word is ${kind}?`, options: opts, answer: opts.indexOf(w) });
    }
    return out;
  }

  /* ============================ NOUNS ============================ */
  const nouns = [
    { q: "A noun is a naming word. Which word is a NOUN?", options: ["quickly", "garden", "happy", "ran"], answer: 1 },
    { q: "Find the noun: \"The kitten was shaking in the bush.\"", options: ["was", "shaking", "kitten", "in"], answer: 2 },
    { q: "Which is a PROPER noun (a special name)?", options: ["city", "Mia", "river", "dog"], answer: 1 },
    { q: "What is the plural of \"child\"?", options: ["childs", "childes", "children", "childrens"], answer: 2 },
    { q: "What is the plural of \"mouse\"?", options: ["mouses", "mice", "mouse", "mices"], answer: 1 },
    { q: "What is the plural of \"box\"?", options: ["boxs", "boxes", "boxen", "box"], answer: 1 },
    { q: "What is the plural of \"baby\"?", options: ["babys", "babyes", "babies", "babi"], answer: 2 },
    { q: "Which sentence has a proper noun?", options: ["the boy ran fast", "We went to London.", "she has a cat", "it is cold"], answer: 1 },
    { q: "Find the noun: \"Ali kicked the bright red ball.\"", options: ["kicked", "bright", "ball", "red"], answer: 2 },
    { q: "A collective noun names a group. Pick one:", options: ["a swarm of bees", "happily", "running", "very fast"], answer: 0 },
    { q: "Which word is a noun?", options: ["sleep (the rest you get)", "loudly", "purple", "between"], answer: 0 },
    { q: "Which group is ALL nouns?", options: ["dog, table, school", "run, jump, sing", "big, red, soft", "he, she, it"], answer: 0 },
    { q: "What is the plural of \"leaf\"?", options: ["leafs", "leaves", "leafes", "leave"], answer: 1 },
    { q: "Find the noun: \"They carried the kitten home.\"", options: ["carried", "kitten", "quickly", "they"], answer: 1 },
    { q: "Which is an abstract noun (a feeling/idea)?", options: ["chair", "kindness", "jump", "green"], answer: 1 },
    { q: "Pick the proper noun:", options: ["country", "Malaysia", "teacher", "school"], answer: 1 },
    { q: "What is the plural of \"tooth\"?", options: ["tooths", "teeth", "toothes", "teeths"], answer: 1 },
    { q: "Which word names a place?", options: ["library", "shout", "tiny", "slowly"], answer: 0 }
  ].concat(
    identify("a NOUN (a naming word)", NOUNS, [ADJS, VERBS, ["quickly", "very", "softly", "under", "and", "but"]], 16)
  );

  /* ============================ VERBS ============================ */
  const verbs = [
    { q: "A verb is an action word. Which word is a VERB?", options: ["table", "jumped", "yellow", "slowly"], answer: 1 },
    { q: "Choose the verb: \"The boy ___ across the road dangerously.\"", options: ["runs", "road", "boy", "dangerous"], answer: 0 },
    { q: "Choose the verb: \"The phone ___ at 12 midnight.\"", options: ["loud", "rang", "midnight", "phone"], answer: 1 },
    { q: "Choose the verb: \"The lion's roar ___ through the forest.\"", options: ["forest", "echoed", "roar", "loud"], answer: 1 },
    { q: "Choose the best verb: \"The caterpillar ___ on green leaves.\"", options: ["climbed", "drank", "flew", "swam"], answer: 0 },
    { q: "Choose the best verb: \"The children ___ when they heard the music.\"", options: ["gathered", "melted", "boiled", "printed"], answer: 0 },
    { q: "Choose the best verb: \"The guests ___ around Ethan.\"", options: ["danced", "fried", "typed", "dug"], answer: 0 },
    { q: "What is the past tense of \"run\"?", options: ["runned", "ran", "runed", "running"], answer: 1 },
    { q: "What is the past tense of \"eat\"?", options: ["eated", "ate", "eaten", "eats"], answer: 1 },
    { q: "What is the past tense of \"swim\"?", options: ["swimmed", "swam", "swum", "swims"], answer: 1 },
    { q: "What is the past tense of \"bring\"?", options: ["bringed", "brang", "brought", "broughted"], answer: 2 },
    { q: "What is the past tense of \"catch\"?", options: ["catched", "caught", "cotch", "catches"], answer: 1 },
    { q: "Find the verb: \"The cow eats the meadow grass.\"", options: ["cow", "eats", "grass", "meadow"], answer: 1 },
    { q: "Which group is ALL verbs?", options: ["sing, jump, read", "cat, dog, fish", "big, small, tall", "he, it, they"], answer: 0 },
    { q: "Choose the verb: \"Mum ___ delicious dishes.\"", options: ["cooks", "kitchen", "tasty", "plate"], answer: 0 },
    { q: "What is the past tense of \"sing\"?", options: ["singed", "sang", "sung", "singped"], answer: 1 },
    { q: "Which word is an action word?", options: ["whispered", "quiet", "darkness", "under"], answer: 0 },
    { q: "Choose the verb: \"The guitarist ___ his guitar proudly.\"", options: ["stage", "plays", "proud", "loud"], answer: 1 },
    /* ----- 50 added "choose the correct verb" questions ----- */
    { q: "The monkey ___ the tree.",                 options: ["climbs", "eats", "swims", "sings"],           answer: 0 },
    { q: "The lion ___ loudly.",                     options: ["dances", "roars", "jumps", "paints"],          answer: 1 },
    { q: "The bird ___ in the sky.",                 options: ["flies", "crawls", "digs", "hides"],            answer: 0 },
    { q: "The rabbit ___ quickly.",                  options: ["runs", "sleeps", "reads", "writes"],           answer: 0 },
    { q: "The fish ___ in the pond.",                options: ["swims", "climbs", "drives", "flies"],          answer: 0 },
    { q: "The baby ___ loudly.",                     options: ["cries", "climbs", "jumps", "paints"],          answer: 0 },
    { q: "The teacher ___ the lesson.",              options: ["teaches", "swims", "dances", "hides"],         answer: 0 },
    { q: "The dog ___ at the stranger.",             options: ["barks", "sings", "reads", "cooks"],            answer: 0 },
    { q: "The cat ___ the milk.",                    options: ["drinks", "climbs", "throws", "dances"],        answer: 0 },
    { q: "The children ___ football.",               options: ["play", "sleep", "draw", "cry"],                answer: 0 },
    { q: "The chef ___ dinner.",                     options: ["cooks", "jumps", "hides", "sings"],            answer: 0 },
    { q: "The student ___ his homework.",            options: ["finishes", "swims", "dances", "climbs"],       answer: 0 },
    { q: "The frog ___ into the pond.",              options: ["jumps", "paints", "writes", "reads"],          answer: 0 },
    { q: "The horse ___ very fast.",                 options: ["runs", "flies", "swims", "hides"],             answer: 0 },
    { q: "The girl ___ a storybook.",                options: ["reads", "barks", "digs", "jumps"],             answer: 0 },
    { q: "The farmer ___ vegetables.",               options: ["grows", "swims", "dances", "paints"],          answer: 0 },
    { q: "The elephant ___ water.",                  options: ["sprays", "climbs", "reads", "writes"],         answer: 0 },
    { q: "The mother ___ breakfast.",                options: ["prepares", "flies", "hides", "dances"],        answer: 0 },
    { q: "The baby bird ___ for food.",              options: ["chirps", "paints", "swims", "digs"],           answer: 0 },
    { q: "The firefighter ___ the fire.",            options: ["fights", "sings", "climbs", "reads"],          answer: 0 },
    { q: "The boy ___ his bicycle.",                 options: ["rides", "swims", "paints", "hides"],           answer: 0 },
    { q: "The monkey ___ bananas.",                  options: ["eats", "drives", "writes", "sings"],           answer: 0 },
    { q: "The children ___ happily.",                options: ["laugh", "crawl", "paint", "bark"],             answer: 0 },
    { q: "The girl ___ beautifully.",                options: ["sings", "digs", "jumps", "hides"],             answer: 0 },
    { q: "The turtle ___ slowly.",                   options: ["walks", "flies", "dances", "paints"],          answer: 0 },
    { q: "The kangaroo ___ high.",                   options: ["jumps", "swims", "writes", "reads"],           answer: 0 },
    { q: "The father ___ the car.",                  options: ["washes", "climbs", "sings", "digs"],           answer: 0 },
    { q: "The duck ___ in the pond.",                options: ["swims", "drives", "paints", "hides"],          answer: 0 },
    { q: "The carpenter ___ the table.",             options: ["builds", "swims", "sings", "jumps"],           answer: 0 },
    { q: "The dog ___ the ball.",                    options: ["catches", "paints", "reads", "writes"],        answer: 0 },
    { q: "The bee ___ around the flowers.",          options: ["buzzes", "crawls", "digs", "hides"],           answer: 0 },
    { q: "The girl ___ her teeth.",                  options: ["brushes", "climbs", "paints", "swims"],        answer: 0 },
    { q: "The students ___ quietly.",                options: ["listen", "bark", "jump", "dig"],               answer: 0 },
    { q: "The tiger ___ in the jungle.",             options: ["hunts", "dances", "reads", "writes"],          answer: 0 },
    { q: "The boy ___ the window.",                  options: ["opens", "swims", "sings", "hides"],            answer: 0 },
    { q: "The bird ___ a nest.",                     options: ["builds", "paints", "drives", "jumps"],         answer: 0 },
    { q: "The children ___ in the playground.",      options: ["play", "bark", "crawl", "dig"],                answer: 0 },
    { q: "The baby ___ milk.",                       options: ["drinks", "climbs", "paints", "sings"],         answer: 0 },
    { q: "The fox ___ the chicken.",                 options: ["chases", "swims", "reads", "writes"],          answer: 0 },
    { q: "The teacher ___ the students.",            options: ["helps", "flies", "dances", "hides"],           answer: 0 },
    { q: "The squirrel ___ nuts.",                   options: ["collects", "swims", "paints", "digs"],         answer: 0 },
    { q: "The boy ___ his shoes.",                   options: ["ties", "sings", "crawls", "hides"],            answer: 0 },
    { q: "The cat ___ on the sofa.",                 options: ["sleeps", "drives", "paints", "writes"],        answer: 0 },
    { q: "The doctor ___ sick people.",              options: ["treats", "jumps", "swims", "digs"],            answer: 0 },
    { q: "The girl ___ her homework neatly.",        options: ["writes", "barks", "climbs", "paints"],         answer: 0 },
    { q: "The lion ___ the meat.",                   options: ["eats", "sings", "drives", "hides"],            answer: 0 },
    { q: "The children ___ their hands.",            options: ["wash", "crawl", "paint", "bark"],              answer: 0 },
    { q: "The frog ___ loudly at night.",            options: ["croaks", "swims", "writes", "reads"],          answer: 0 },
    { q: "The baker ___ bread every morning.",       options: ["bakes", "climbs", "dances", "hides"],          answer: 0 },
    { q: "The police officer ___ the traffic.",      options: ["controls", "swims", "paints", "jumps"],        answer: 0 }
  ].concat(
    identify("a VERB (an action word)", VERBS, [NOUNS, ADJS, ["very", "slowly", "here", "and"]], 16)
  );

  /* ========================= PRESENT TENSE ========================= */
  const present_tense = [
    { q: "She ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1 },
    { q: "They ___ football after class.", options: ["plays", "play", "playing", "played"], answer: 1 },
    { q: "He ___ his homework now.", options: ["do", "does", "doing", "done"], answer: 1 },
    { q: "I ___ cleaning up my room now.", options: ["is", "are", "am", "be"], answer: 2 },
    { q: "The cat ___ on the soft mat.", options: ["sit", "sits", "sitting", "sat"], answer: 1 },
    { q: "We ___ English on Mondays.", options: ["learns", "learn", "learning", "learnt"], answer: 1 },
    { q: "My brother ___ TV every evening.", options: ["watch", "watches", "watching", "watched"], answer: 1 },
    { q: "The birds ___ in the morning.", options: ["sings", "sing", "singing", "sang"], answer: 1 },
    { q: "Which sentence is in the PRESENT tense?", options: ["She walked home.", "She walks home.", "She will walk home.", "She had walked home."], answer: 1 },
    { q: "It ___ heavily outside right now.", options: ["rain", "rains", "is raining", "rained"], answer: 2 },
    { q: "Ashley ___ to a cooking channel.", options: ["subscribe", "subscribes", "subscribing", "subscribed"], answer: 1 },
    { q: "The baby ___ when it is hungry.", options: ["cry", "cries", "crying", "cried"], answer: 1 },
    { q: "Dad ___ on the radio to listen to his song.", options: ["turn", "turns", "turning", "turned"], answer: 1 },
    { q: "You ___ very fast.", options: ["runs", "run", "running", "ran"], answer: 1 },
    { q: "The teacher ___ a story to the class.", options: ["read", "reads", "reading", "readed"], answer: 1 },
    { q: "Which is correct present tense?", options: ["He eat rice.", "He eats rice.", "He eating rice.", "He eaten rice."], answer: 1 },
    { q: "She ___ her teeth before bed.", options: ["brush", "brushes", "brushing", "brushed"], answer: 1 },
    { q: "The dogs ___ loudly at strangers.", options: ["barks", "bark", "barking", "barked"], answer: 1 },
    { q: "Mia ___ her best friend every weekend.", options: ["visit", "visits", "visiting", "visited"], answer: 1 },
    { q: "Which sentence uses present continuous correctly?", options: ["He is run.", "He is running.", "He running.", "He runs is."], answer: 1 },
    { q: "I ___ a pet rabbit at home.", options: ["has", "have", "having", "had"], answer: 1 },
    { q: "Preston ___ his bicycle to school.", options: ["ride", "rides", "riding", "rode"], answer: 1 },
    { q: "The sun ___ in the east.", options: ["rise", "rises", "rising", "rose"], answer: 1 },
    { q: "We ___ happy when we win.", options: ["is", "are", "am", "be"], answer: 1 },
    { q: "She always ___ her homework on time.", options: ["finish", "finishes", "finishing", "finished"], answer: 1 },
    /* ----- 50 added present-tense questions ----- */
    { q: "She ___ to school every day.",                    options: ["go", "goes", "going", "gone"],                  answer: 1 },
    { q: "They ___ football after school.",                 options: ["plays", "play", "playing", "played"],           answer: 1 },
    { q: "The cat ___ milk every morning.",                 options: ["drink", "drinks", "drinking", "drank"],         answer: 1 },
    { q: "We ___ our homework at night.",                   options: ["does", "do", "doing", "did"],                   answer: 1 },
    { q: "He ___ very fast.",                               options: ["run", "runs", "running", "ran"],                answer: 1 },
    { q: "The birds ___ in the sky.",                       options: ["flies", "fly", "flying", "flew"],               answer: 1 },
    { q: "My mother ___ dinner daily.",                     options: ["cook", "cooks", "cooking", "cooked"],           answer: 1 },
    { q: "I ___ my teeth twice a day.",                     options: ["brush", "brushes", "brushing", "brushed"],      answer: 0 },
    { q: "The boys ___ loudly.",                            options: ["shout", "shouts", "shouting", "shouted"],       answer: 0 },
    { q: "Sarah ___ storybooks every night.",               options: ["read", "reads", "reading", "readed"],           answer: 1 },
    { q: "The dog ___ at strangers.",                       options: ["bark", "barks", "barking", "barked"],           answer: 1 },
    { q: "We ___ to the park every Sunday.",                options: ["go", "goes", "going", "gone"],                  answer: 0 },
    { q: "The teacher ___ English.",                        options: ["teach", "teaches", "teaching", "taught"],       answer: 1 },
    { q: "My father ___ the car every weekend.",            options: ["wash", "washes", "washing", "washed"],          answer: 1 },
    { q: "The fish ___ in the pond.",                       options: ["swims", "swim", "swimming", "swam"],            answer: 0 },
    { q: "The baby ___ loudly at night.",                   options: ["cry", "cries", "crying", "cried"],              answer: 1 },
    { q: "They ___ their classroom clean.",                 options: ["keep", "keeps", "keeping", "kept"],             answer: 0 },
    { q: "Ali ___ breakfast at 7 a.m.",                     options: ["eat", "eats", "eating", "ate"],                 answer: 1 },
    { q: "The children ___ in the playground.",             options: ["plays", "play", "playing", "played"],           answer: 1 },
    { q: "My sister ___ beautifully.",                      options: ["sing", "sings", "singing", "sang"],             answer: 1 },
    { q: "The rabbit ___ quickly.",                         options: ["hop", "hops", "hopping", "hopped"],             answer: 1 },
    { q: "We ___ television at night.",                     options: ["watch", "watches", "watching", "watched"],      answer: 0 },
    { q: "The lion ___ loudly.",                            options: ["roar", "roars", "roaring", "roared"],           answer: 1 },
    { q: "I ___ water every morning.",                      options: ["drink", "drinks", "drinking", "drank"],         answer: 0 },
    { q: "The teacher ___ the students.",                   options: ["help", "helps", "helping", "helped"],           answer: 1 },
    { q: "Tom ___ his bicycle carefully.",                  options: ["ride", "rides", "riding", "rode"],              answer: 1 },
    { q: "The ducks ___ in the pond.",                      options: ["swims", "swim", "swimming", "swam"],            answer: 1 },
    { q: "My brother ___ comics.",                          options: ["read", "reads", "reading", "readed"],           answer: 1 },
    { q: "The monkey ___ bananas.",                         options: ["eat", "eats", "eating", "ate"],                 answer: 1 },
    { q: "We ___ our friends every weekend.",               options: ["visit", "visits", "visiting", "visited"],       answer: 0 },
    { q: "The baby ___ milk.",                              options: ["drink", "drinks", "drinking", "drank"],         answer: 1 },
    { q: "The boys ___ basketball after school.",           options: ["plays", "play", "playing", "played"],           answer: 1 },
    { q: "My grandmother ___ cookies.",                     options: ["bake", "bakes", "baking", "baked"],             answer: 1 },
    { q: "The students ___ quietly in class.",              options: ["sit", "sits", "sitting", "sat"],                answer: 0 },
    { q: "She ___ her bag neatly.",                         options: ["pack", "packs", "packing", "packed"],           answer: 1 },
    { q: "The tiger ___ in the jungle.",                    options: ["live", "lives", "living", "lived"],             answer: 1 },
    { q: "I ___ my room every Saturday.",                   options: ["clean", "cleans", "cleaning", "cleaned"],       answer: 0 },
    { q: "The cat ___ on the sofa.",                        options: ["sleep", "sleeps", "sleeping", "slept"],         answer: 1 },
    { q: "The children ___ happily together.",              options: ["laugh", "laughs", "laughing", "laughed"],       answer: 0 },
    { q: "The chef ___ delicious food.",                    options: ["cook", "cooks", "cooking", "cooked"],           answer: 1 },
    { q: "We ___ books from the library.",                  options: ["borrow", "borrows", "borrowing", "borrowed"],   answer: 0 },
    { q: "The horse ___ very fast.",                        options: ["run", "runs", "running", "ran"],                answer: 1 },
    { q: "My mother ___ flowers in the garden.",            options: ["plant", "plants", "planting", "planted"],       answer: 1 },
    { q: "The bee ___ around the flowers.",                 options: ["buzz", "buzzes", "buzzing", "buzzed"],          answer: 1 },
    { q: "The girl ___ her homework neatly.",               options: ["write", "writes", "writing", "wrote"],          answer: 1 },
    { q: "The boys ___ their hands before eating.",         options: ["wash", "washes", "washing", "washed"],          answer: 0 },
    { q: "My teacher ___ kind to everyone.",                options: ["is", "are", "were", "am"],                      answer: 0 },
    { q: "The stars ___ brightly at night.",                options: ["shines", "shine", "shining", "shined"],         answer: 1 },
    { q: "The farmer ___ vegetables every year.",           options: ["grow", "grows", "growing", "grew"],             answer: 1 },
    { q: "The children ___ to music every evening.",        options: ["listen", "listens", "listening", "listened"],   answer: 0 }
  ];

  /* =========================== PRONOUNS =========================== */
  const pronouns = [
    { q: "Mia lost ___ book. (Mia is a girl)", options: ["his", "her", "their", "its"], answer: 1 },
    { q: "Ali and I are friends. ___ play together.", options: ["He", "We", "They", "She"], answer: 1 },
    { q: "Give the ball to ___ . (the boy)", options: ["he", "him", "his", "they"], answer: 1 },
    { q: "The dog wagged ___ tail.", options: ["his", "her", "its", "their"], answer: 2 },
    { q: "Replace the name: \"Sarah is kind.\" → \"___ is kind.\"", options: ["He", "She", "It", "They"], answer: 1 },
    { q: "This book is mine. That one is ___ . (belongs to you)", options: ["your", "yours", "you", "their"], answer: 1 },
    { q: "The students finished ___ work.", options: ["his", "her", "their", "its"], answer: 2 },
    { q: "Can you help ___ ? (me, the speaker)", options: ["I", "me", "my", "mine"], answer: 1 },
    { q: "Tom and Ben are late. ___ missed the bus.", options: ["He", "She", "They", "It"], answer: 2 },
    { q: "Which word is a pronoun?", options: ["table", "she", "jump", "blue"], answer: 1 },
    { q: "The cat licked ___ paws.", options: ["it", "its", "it's", "their"], answer: 1 },
    { q: "\"___ am going to the park,\" said Ravi.", options: ["I", "Me", "My", "Mine"], answer: 0 },
    { q: "The gift is for ___ . (Anna)", options: ["she", "her", "hers", "they"], answer: 1 },
    { q: "Mum baked a cake. ___ smells lovely.", options: ["He", "She", "It", "They"], answer: 2 },
    { q: "We saw ___ at the shop. (the two girls)", options: ["they", "them", "their", "theirs"], answer: 1 },
    { q: "Which pronoun replaces \"the football team\"?", options: ["he", "she", "it/they", "I"], answer: 2 },
    { q: "That bag is ___ . (belongs to me)", options: ["my", "mine", "me", "I"], answer: 1 },
    { q: "Olivia's father reads ___ newspaper.", options: ["her", "his", "their", "its"], answer: 1 },
    { q: "Pick the correct pronoun: \"___ is my best friend.\" (a boy named Sam)", options: ["He", "Him", "His", "It"], answer: 0 },
    { q: "The children hid ___ under the bed.", options: ["theirselves", "themselves", "themself", "theirself"], answer: 1 },
    { q: "Which is a possessive pronoun?", options: ["run", "ours", "loud", "and"], answer: 1 },
    { q: "I will do it ___ . (no help)", options: ["myself", "meself", "my self", "I self"], answer: 0 },
    { q: "\"Where are ___ going?\" she asked the boys.", options: ["you", "your", "yours", "yourself"], answer: 0 },
    { q: "The keys are ___ . (belong to them)", options: ["their", "theirs", "them", "they"], answer: 1 },
    /* ----- 50 added "pick the right pronoun" questions ----- */
    { q: "Ali is my friend. ___ is kind.",                                  options: ["He", "She", "It", "They"], answer: 0 },
    { q: "Sara is singing. ___ has a nice voice.",                          options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The cat is sleeping. ___ is tired.",                              options: ["He", "She", "It", "They"], answer: 2 },
    { q: "Tom and Ben are brothers. ___ play football.",                    options: ["He", "She", "It", "They"], answer: 3 },
    { q: "I have a bird. ___ can fly.",                                     options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My mother is cooking. ___ is busy.",                              options: ["He", "She", "It", "They"], answer: 1 },
    { q: "John is reading a book. ___ likes stories.",                      options: ["He", "She", "It", "They"], answer: 0 },
    { q: "The girls are dancing. ___ are happy.",                           options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The dog is barking. ___ is noisy.",                               options: ["He", "She", "It", "They"], answer: 2 },
    { q: "Amy is my cousin. ___ is funny.",                                 options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The boys are playing. ___ are excited.",                          options: ["He", "She", "It", "They"], answer: 3 },
    { q: "My father is driving. ___ is careful.",                           options: ["He", "She", "It", "They"], answer: 0 },
    { q: "The baby is crying. ___ is hungry.",                              options: ["He", "She", "It", "They"], answer: 1 },
    { q: "Lisa and Jenny are friends. ___ study together.",                 options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The fish is swimming. ___ is fast.",                              options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My teacher is kind. ___ helps us.",                               options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The rabbits are hopping. ___ are cute.",                          options: ["He", "She", "It", "They"], answer: 3 },
    { q: "Daniel is laughing. ___ is happy.",                               options: ["He", "She", "It", "They"], answer: 0 },
    { q: "The monkey is climbing. ___ is quick.",                           options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My sisters are singing. ___ love music.",                         options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The tiger is sleeping. ___ is tired.",                            options: ["He", "She", "It", "They"], answer: 2 },
    { q: "Sarah is reading. ___ likes books.",                              options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The ducks are swimming. ___ are in the pond.",                    options: ["He", "She", "It", "They"], answer: 3 },
    { q: "My brother is tall. ___ plays basketball.",                       options: ["He", "She", "It", "They"], answer: 0 },
    { q: "The baby birds are hungry. ___ are chirping loudly.",             options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The elephant is big. ___ is strong.",                             options: ["He", "She", "It", "They"], answer: 2 },
    { q: "The children are studying. ___ are quiet.",                       options: ["He", "She", "It", "They"], answer: 3 },
    { q: "My aunt is a doctor. ___ works at a hospital.",                   options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The puppy is playful. ___ likes running.",                        options: ["He", "She", "It", "They"], answer: 2 },
    { q: "Ben and I are classmates. ___ study together.",                   options: ["He", "She", "We", "It"],   answer: 2 },
    { q: "I am hungry. ___ want to eat.",                                   options: ["He", "She", "I", "They"],   answer: 2 },
    { q: "My parents are kind. ___ help me a lot.",                         options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The owl is sitting on the tree. ___ is quiet.",                   options: ["He", "She", "It", "They"], answer: 2 },
    { q: "Jenny is my friend. ___ likes drawing.",                          options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The lions are roaring. ___ are loud.",                            options: ["He", "She", "It", "They"], answer: 3 },
    { q: "My grandfather is reading the newspaper. ___ wears glasses.",     options: ["He", "She", "It", "They"], answer: 0 },
    { q: "The cat is under the table. ___ is hiding.",                      options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My cousins are visiting us. ___ arrived this morning.",           options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The butterfly is beautiful. ___ has colourful wings.",            options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My sister and I are baking cookies. ___ are having fun.",         options: ["He", "She", "We", "It"],   answer: 2 },
    { q: "The frog is jumping. ___ is green.",                              options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My uncle is a farmer. ___ grows vegetables.",                     options: ["He", "She", "It", "They"], answer: 0 },
    { q: "The students are in the classroom. ___ are listening carefully.", options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The horse is running fast. ___ is strong.",                       options: ["He", "She", "It", "They"], answer: 2 },
    { q: "Emma is carrying a bag. ___ is walking home.",                    options: ["He", "She", "It", "They"], answer: 1 },
    { q: "The chickens are eating corn. ___ are hungry.",                   options: ["He", "She", "It", "They"], answer: 3 },
    { q: "My brother and I like football. ___ play every weekend.",         options: ["He", "She", "We", "It"],   answer: 2 },
    { q: "The turtle is slow. ___ walks carefully.",                        options: ["He", "She", "It", "They"], answer: 2 },
    { q: "My friends are at the playground. ___ are playing happily.",      options: ["He", "She", "It", "They"], answer: 3 },
    { q: "The baby is sleeping. ___ is quiet now.",                         options: ["He", "She", "It", "They"], answer: 1 }
  ];

  /* ========================== ADJECTIVES ========================== */
  const adjectives = [
    { q: "An adjective describes a noun. Which is an ADJECTIVE?", options: ["run", "spiky", "table", "quickly"], answer: 1 },
    { q: "Find the adjective: \"It looks frightened.\"", options: ["looks", "it", "frightened", "very"], answer: 2 },
    { q: "Find the adjective: \"They kicked a bright red ball.\"", options: ["kicked", "ball", "bright", "they"], answer: 2 },
    { q: "Which word describes how something looks?", options: ["beautiful", "jumped", "school", "loudly"], answer: 0 },
    { q: "The opposite adjective of \"loud\" is:", options: ["quiet", "louder", "loudly", "noise"], answer: 0 },
    { q: "Comparative: big → ___", options: ["biger", "bigger", "biggest", "more big"], answer: 1 },
    { q: "Superlative: tall → the ___", options: ["taller", "tallest", "most tall", "tallter"], answer: 1 },
    { q: "Which sentence has an adjective?", options: ["The dog barked.", "The fluffy dog barked.", "It barked loudly.", "Dogs bark."], answer: 1 },
    { q: "Comparative: good → ___", options: ["gooder", "more good", "better", "best"], answer: 2 },
    { q: "Superlative: bad → the ___", options: ["baddest", "worse", "worst", "more bad"], answer: 2 },
    { q: "Pick the adjective in: \"a rough and bumpy footpath\"", options: ["footpath", "rough", "and", "a"], answer: 1 },
    { q: "Which group is ALL adjectives?", options: ["soft, wild, broken", "run, sing, eat", "cow, road, gate", "he, she, it"], answer: 0 },
    { q: "The ___ monster roared. (describing word)", options: ["enormous", "quickly", "roared", "monster"], answer: 0 },
    { q: "Which describes a feeling?", options: ["happy", "table", "run", "under"], answer: 0 },
    { q: "Comparative: happy → ___", options: ["happyer", "happier", "happiest", "more happy"], answer: 1 },
    { q: "Find the adjective: \"The rotten fruit smelled bad.\"", options: ["fruit", "rotten", "smelled", "the"], answer: 1 },
    { q: "Which word can describe a noun like \"night\"?", options: ["dark", "ran", "quickly", "and"], answer: 0 },
    /* ----- 50 added "choose the correct adjective" questions ----- */
    { q: "The lion is very ___.",                  options: ["fierce", "table", "jump", "swim"],          answer: 0 },
    { q: "The kitten is ___.",                     options: ["soft", "run", "pencil", "climb"],            answer: 0 },
    { q: "The elephant is very ___.",              options: ["huge", "write", "lamp", "sing"],             answer: 0 },
    { q: "The girl wore a ___ dress.",             options: ["beautiful", "book", "jump", "apple"],        answer: 0 },
    { q: "The soup is very ___.",                  options: ["hot", "swim", "chair", "dance"],             answer: 0 },
    { q: "The ice cream is ___.",                  options: ["cold", "drive", "spoon", "fly"],             answer: 0 },
    { q: "The rabbit is very ___.",                options: ["quick", "table", "write", "climb"],          answer: 0 },
    { q: "The baby is ___.",                       options: ["sleepy", "jump", "clock", "sing"],           answer: 0 },
    { q: "The flowers are ___.",                   options: ["colorful", "swim", "pencil", "crawl"],       answer: 0 },
    { q: "The tiger is very ___.",                 options: ["strong", "plate", "drive", "paint"],         answer: 0 },
    { q: "The old house looks ___.",               options: ["scary", "jump", "spoon", "climb"],           answer: 0 },
    { q: "The puppy is very ___.",                 options: ["playful", "chair", "swim", "write"],         answer: 0 },
    { q: "The road is very ___.",                  options: ["narrow", "sing", "apple", "dance"],          answer: 0 },
    { q: "The mountain is very ___.",              options: ["tall", "spoon", "drive", "swim"],            answer: 0 },
    { q: "The baby bird is very ___.",             options: ["tiny", "pencil", "jump", "crawl"],           answer: 0 },
    { q: "The cake tastes ___.",                   options: ["delicious", "chair", "climb", "write"],      answer: 0 },
    { q: "The snake is very ___.",                 options: ["long", "table", "dance", "paint"],           answer: 0 },
    { q: "The pillow is very ___.",                options: ["soft", "spoon", "swim", "drive"],            answer: 0 },
    { q: "The clown is very ___.",                 options: ["funny", "jump", "apple", "write"],           answer: 0 },
    { q: "The fox is very ___.",                   options: ["clever", "chair", "climb", "sing"],          answer: 0 },
    { q: "The water is very ___.",                 options: ["clear", "pencil", "dance", "swim"],          answer: 0 },
    { q: "The dragon is very ___.",                options: ["dangerous", "spoon", "jump", "write"],       answer: 0 },
    { q: "The little girl is very ___.",           options: ["kind", "table", "drive", "crawl"],           answer: 0 },
    { q: "The classroom is very ___.",             options: ["noisy", "apple", "climb", "sing"],           answer: 0 },
    { q: "The moon looks very ___.",               options: ["bright", "spoon", "dance", "paint"],         answer: 0 },
    { q: "The monkey is very ___.",                options: ["naughty", "chair", "swim", "write"],         answer: 0 },
    { q: "The weather is very ___.",               options: ["windy", "pencil", "jump", "crawl"],          answer: 0 },
    { q: "The farmer is very ___.",                options: ["hardworking", "spoon", "climb", "dance"],    answer: 0 },
    { q: "The stars are very ___.",                options: ["shiny", "apple", "write", "swim"],           answer: 0 },
    { q: "The little boy is very ___.",            options: ["brave", "chair", "crawl", "sing"],           answer: 0 },
    { q: "The sandwich tastes ___.",               options: ["tasty", "spoon", "jump", "paint"],           answer: 0 },
    { q: "The old man is very ___.",               options: ["wise", "pencil", "climb", "dance"],          answer: 0 },
    { q: "The castle is very ___.",                options: ["enormous", "apple", "swim", "write"],        answer: 0 },
    { q: "The kitten looks ___.",                  options: ["adorable", "chair", "crawl", "sing"],        answer: 0 },
    { q: "The shoes are very ___.",                options: ["dirty", "spoon", "climb", "paint"],          answer: 0 },
    { q: "The little bird is very ___.",           options: ["colorful", "pencil", "jump", "dance"],       answer: 0 },
    { q: "The lion looks ___.",                    options: ["angry", "apple", "swim", "write"],           answer: 0 },
    { q: "The girl is very ___.",                  options: ["cheerful", "chair", "crawl", "sing"],        answer: 0 },
    { q: "The classroom is ___.",                  options: ["clean", "spoon", "climb", "dance"],          answer: 0 },
    { q: "The road is very ___.",                  options: ["busy", "pencil", "jump", "swim"],            answer: 0 },
    { q: "The baby looks ___.",                    options: ["happy", "chair", "crawl", "paint"],          answer: 0 },
    { q: "The owl is very ___.",                   options: ["quiet", "spoon", "climb", "dance"],          answer: 0 },
    { q: "The cake is very ___.",                  options: ["sweet", "apple", "swim", "write"],           answer: 0 },
    { q: "The horse is very ___.",                 options: ["fast", "pencil", "jump", "crawl"],           answer: 0 },
    { q: "The fox is very ___.",                   options: ["sly", "chair", "climb", "sing"],             answer: 0 },
    { q: "The room is very ___.",                  options: ["messy", "spoon", "dance", "paint"],          answer: 0 },
    { q: "The children are very ___.",             options: ["excited", "apple", "swim", "write"],         answer: 0 },
    { q: "The puppy is very ___.",                 options: ["cute", "chair", "crawl", "sing"],            answer: 0 },
    { q: "The mountain looks ___.",                options: ["majestic", "spoon", "jump", "paint"],        answer: 0 },
    { q: "The river is very ___.",                 options: ["deep", "pencil", "climb", "dance"],          answer: 0 }
  ].concat(
    identify("an ADJECTIVE (a describing word)", ADJS, [NOUNS, VERBS, ["quickly", "and", "under", "very", "slowly"]], 17)
  );

  /* ========================== PUNCTUATION ========================== */
  const punctuation = [
    { q: "Which sentence is punctuated correctly?", options: ["did you enjoy reading that book", "Did you enjoy reading that book?", "did you enjoy reading that book.", "Did you enjoy reading that book"], answer: 1 },
    { q: "Which end mark fits? \"Do kittens like to drink milk__\"", options: [".", "?", "!", ","], answer: 1 },
    { q: "Which end mark fits? \"Watch out__\"", options: [".", "?", "!", ","], answer: 2 },
    { q: "Which sentence has correct capital letters?", options: ["my name is sam.", "My name is Sam.", "my Name is sam.", "MY name is sam."], answer: 1 },
    { q: "Choose the correctly punctuated sentence:", options: ["i live in london", "I live in London.", "i live in London", "I live in london."], answer: 1 },
    { q: "Which list uses commas correctly?", options: ["I bought apples bananas and pears.", "I bought apples, bananas and pears.", "I bought, apples bananas, and pears.", "I bought apples bananas, and, pears."], answer: 1 },
    { q: "Where does the apostrophe go? \"The dogs bone\" (one dog)", options: ["dog's bone", "dogs' bone", "dog's' bone", "dogs's bone"], answer: 0 },
    { q: "Which is the correct contraction for \"do not\"?", options: ["dont", "do'nt", "don't", "don,t"], answer: 2 },
    { q: "Pick the sentence with correct quotation marks:", options: ['"Come here!" Ali called.', 'Come here! Ali called.', '"Come here! Ali called.', 'Come here," Ali called.'], answer: 0 },
    { q: "Which sentence ends correctly?", options: ["The lion was caught in a net?", "The lion was caught in a net.", "the lion was caught in a net", "The lion was caught in a net,"], answer: 1 },
    { q: "What punctuation begins and a question need?", options: ["A capital + .", "A capital + ?", "lowercase + ?", "A capital + !"], answer: 1 },
    { q: "Which sentence is correct?", options: ["she said \"hello\"", "She said, \"Hello!\"", "she Said, hello!", "She said \"hello\""], answer: 1 },
    { q: "Add the comma: \"Yes I will help you.\"", options: ["Yes, I will help you.", "Yes I, will help you.", "Yes I will, help you.", "Yes I will help, you."], answer: 0 },
    { q: "Which uses an apostrophe correctly (belonging to Mia)?", options: ["Mias book", "Mia's book", "Mias' book", "Mia,s book"], answer: 1 },
    { q: "Which sentence is written correctly?", options: ["what time is it.", "What time is it?", "what time is it?", "What time is it"], answer: 1 },
    { q: "Pick the correctly punctuated sentence:", options: ["mum is on her way back.", "Mum is on her way back.", "mum is on her way back", "Mum is on her way back"], answer: 1 },
    { q: "Which is correct?", options: ["Its raining today.", "It's raining today.", "Its' raining today.", "Its raining today"], answer: 1 },
    { q: "Choose the sentence with a correct exclamation:", options: ["The house is on fire.", "The house is on fire!", "the house is on fire", "The house is on fire?"], answer: 1 },
    { q: "Which sentence uses a full stop correctly?", options: ["I like to read books", "I like to read books.", "i like to read books.", "I like, to read books"], answer: 1 },
    { q: "What is missing? \"can you swim\"", options: ["Capital C and ?", "only a .", "nothing", "Capital C and ."], answer: 0 },
    { q: "Which sentence is correct?", options: ["she has a cat, a dog and a fish.", "She has a cat, a dog and a fish.", "She has a cat a dog and a fish", "she has a cat a dog and a fish."], answer: 1 },
    /* ----- 50 added punctuation questions ----- */
    { q: "___ is my best friend.",                                options: ["ali", "Ali", "ali.", "ali?"],                                       answer: 1 },
    { q: "I like apples___",                                      options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "___ are you going?",                                    options: ["Where", "where", "where.", "where!"],                                answer: 0 },
    { q: "Wow___ That is amazing.",                               options: [".", "?", "!", ","],                                                  answer: 2 },
    { q: "The cat is black___ white and brown.",                  options: ["!", "?", ",", "."],                                                  answer: 2 },
    { q: "My name is Tom___",                                     options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "___ did you eat for lunch?",                            options: ["what", "What", "what.", "what!"],                                    answer: 1 },
    { q: "Be careful___",                                         options: ["?", ".", "!", ","],                                                  answer: 2 },
    { q: "I have a pencil___ a ruler and a book.",                options: [".", "?", ",", "!"],                                                  answer: 2 },
    { q: "___ is my teacher.",                                    options: ["mr lim", "Mr Lim", "mr lim.", "mr Lim"],                              answer: 1 },
    { q: "The dog barked loudly___",                              options: [".", "?", ",", "!"],                                                  answer: 0 },
    { q: "___ is your birthday?",                                 options: ["when", "When", "when!", "when."],                                    answer: 1 },
    { q: "Oh no___ I dropped my ice cream.",                      options: [".", "?", "!", ","],                                                  answer: 2 },
    { q: "My favourite colours are red___ blue and green.",       options: [".", ",", "?", "!"],                                                  answer: 1 },
    { q: "We went to the zoo___",                                 options: ["?", ".", "!", ","],                                                  answer: 1 },
    { q: "___ are playing football.",                             options: ["the boys", "The boys", "the Boys", "the boys."],                     answer: 1 },
    { q: "Stop___",                                               options: [".", ",", "!", "?"],                                                  answer: 2 },
    { q: "___ is your bag?",                                      options: ["where", "Where", "where.", "where!"],                                answer: 1 },
    { q: "I saw lions___ tigers and monkeys.",                    options: [".", "?", ",", "!"],                                                  answer: 2 },
    { q: "My brother is funny___",                                options: [".", "?", ",", "!"],                                                  answer: 0 },
    { q: "___ is raining today.",                                 options: ["it", "It", "it.", "it!"],                                            answer: 1 },
    { q: "Hooray___ We won the game.",                            options: [".", "?", "!", ","],                                                  answer: 2 },
    { q: "___ do you go to school?",                              options: ["how", "How", "how.", "how!"],                                        answer: 1 },
    { q: "The baby is sleeping___",                               options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "My favourite animals are rabbits___ cats and birds.",   options: [".", ",", "?", "!"],                                                  answer: 1 },
    { q: "___ is my mother.",                                     options: ["mrs lee", "Mrs Lee", "mrs Lee", "Mrs lee"],                          answer: 1 },
    { q: "Please sit down___",                                    options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "___ are you sad?",                                      options: ["why", "Why", "why!", "why."],                                        answer: 1 },
    { q: "I have two pencils___ three erasers and one ruler.",    options: [".", ",", "?", "!"],                                                  answer: 1 },
    { q: "The bird is singing___",                                options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "___ is my school bag.",                                 options: ["this", "This", "this!", "this."],                                    answer: 1 },
    { q: "Oh dear___ I forgot my homework.",                      options: [".", "!", "?", ","],                                                  answer: 1 },
    { q: "___ is your favourite food?",                           options: ["what", "What", "what!", "what."],                                    answer: 1 },
    { q: "The flowers are beautiful___",                          options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "I bought apples___ oranges and bananas.",               options: [".", "?", ",", "!"],                                                  answer: 2 },
    { q: "___ is my father.",                                     options: ["mr tan", "Mr Tan", "mr tan.", "mr Tan"],                              answer: 1 },
    { q: "Look out___",                                           options: [".", ",", "!", "?"],                                                  answer: 2 },
    { q: "___ are you laughing?",                                 options: ["why", "Why", "why.", "why!"],                                        answer: 1 },
    { q: "The classroom is clean___",                             options: ["?", ".", "!", ","],                                                  answer: 1 },
    { q: "We saw elephants___ giraffes and zebras.",              options: [".", "?", ",", "!"],                                                  answer: 2 },
    { q: "___ is my best friend.",                                options: ["she", "She", "she!", "she."],                                        answer: 1 },
    { q: "Amazing___ That trick was great.",                      options: [".", "?", "!", ","],                                                  answer: 2 },
    { q: "___ do you live?",                                      options: ["where", "Where", "where!", "where."],                                answer: 1 },
    { q: "The boy is reading___",                                 options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "My bag has books___ pencils and crayons.",              options: [".", "?", ",", "!"],                                                  answer: 2 },
    { q: "___ is my classroom.",                                  options: ["this", "This", "this.", "this!"],                                    answer: 1 },
    { q: "Ouch___ That hurts.",                                   options: [".", "?", "!", ","],                                                  answer: 2 },
    { q: "___ is your teacher?",                                  options: ["who", "Who", "who!", "who."],                                        answer: 1 },
    { q: "The children are happy___",                             options: ["?", "!", ".", ","],                                                  answer: 2 },
    { q: "We ate rice___ chicken and vegetables.",                options: [".", "?", ",", "!"],                                                  answer: 2 }
  ];

  /* ============== SENTENCE BUILDING (Sentence Order + Structure merged) ============== */
  const _ARR = "Arrange these words into a correct sentence:";
  const sentence_order = [
    /* word-rearrangement builders */
    { builder: true, q: _ARR, target: "Did you enjoy reading that book?" },
    { builder: true, q: _ARR, target: "Do kittens like to drink milk?" },
    { builder: true, q: _ARR, target: "Squeeze the oranges to make juice." },
    { builder: true, q: _ARR, target: "They carried the kitten home." },
    { builder: true, q: _ARR, target: "Ali kicked the ball." },
    { builder: true, q: _ARR, target: "The dog ran fast." },
    { builder: true, q: _ARR, target: "We went to the park." },
    { builder: true, q: _ARR, target: "I saw a black cat." },
    { builder: true, q: _ARR, target: "She loves ice cream." },
    { builder: true, q: _ARR, target: "She wakes up early in the morning." },
    { builder: true, q: _ARR, target: "Please close the door." },
    { builder: true, q: _ARR, target: "Where are you going?" },
    { builder: true, q: _ARR, target: "It began to rain heavily." },
    { builder: true, q: _ARR, target: "The children hid under the bed." },
    { builder: true, q: _ARR, target: "Mother cooks delicious dishes." },
    { builder: true, q: _ARR, target: "The teachers had a meeting." },
    { builder: true, q: _ARR, target: "I like to read books." },
    { builder: true, q: _ARR, target: "We went swimming yesterday." },
    { builder: true, q: _ARR, target: "The cat sat on the mat." },
    { builder: true, q: _ARR, target: "Wish Ethan a Happy birthday." },
    /* ---- "How sentences are built" — the old sentence-structure MCQ ---- */
    { q: "Choose the best ending: \"Olivia's father reads the newspaper ___\"", options: ["every morning before he goes to work.", "when the witch walked into the room.", "and the cleverest of them all.", "to make orange juice."], answer: 0 },
    { q: "Choose the best ending: \"The children hid under the bed ___\"", options: ["after all the students went home.", "when the witch walked into the room.", "every morning before work.", "on the stage."], answer: 1 },
    { q: "Choose the best ending: \"The guitarist plays his guitar proudly ___\"", options: ["when he is performing on the stage.", "when there is a family gathering.", "before he goes to work.", "into the room."], answer: 0 },
    { q: "Choose the best ending: \"Mother cooks delicious dishes ___\"", options: ["when there is a family gathering.", "when the witch walked in.", "on the stage.", "before he goes to work."], answer: 0 },
    { q: "Choose the best ending: \"The teachers had a meeting ___\"", options: ["after all the students went home.", "when the witch walked in.", "on the stage.", "to make juice."], answer: 0 },
    { q: "Which is a COMPLETE sentence?", options: ["Running very fast.", "The big dog.", "She ran to school.", "Under the old tree."], answer: 2 },
    { q: "Which is NOT a complete sentence?", options: ["Birds can fly.", "The cat sleeps.", "In the dark hall.", "I am happy."], answer: 2 },
    { q: "Join with the best word: \"I was tired ___ I went to bed.\"", options: ["but", "so", "or", "and then maybe"], answer: 1 },
    { q: "Join with the best word: \"She was sad ___ she lost her toy.\"", options: ["because", "but", "or", "so"], answer: 0 },
    { q: "Join with the best word: \"I like tea ___ I do not like coffee.\"", options: ["but", "so", "because", "and the"], answer: 0 },
    { q: "Choose the subject: \"The frightened kitten hid in the bush.\"", options: ["hid", "in the bush", "The frightened kitten", "bush"], answer: 2 },
    { q: "Choose the action part: \"Ali and Mia played at the park.\"", options: ["Ali and Mia", "played at the park", "at", "the park"], answer: 1 },
    { q: "Which word completes it best? \"Mr Fox was too ___ for them.\"", options: ["clever", "pencil", "goose", "nose"], answer: 0 },
    { q: "Which word completes it best? \"Bunce was a duck and ___ farmer.\"", options: ["apple", "goose", "pencil", "clever"], answer: 1 },
    { q: "Which makes a natural sentence?", options: ["She picked up the kitten gently.", "Gently she the kitten picked up.", "Picked she gently up the kitten.", "The kitten gently picked she up."], answer: 0 },
    /* ----- 50 word-rearrangement builders (from your big list) ----- */
    { builder: true, q: _ARR, target: "Jenny likes ice cream.",                 words: ["Jenny", "likes", "ice cream."] },
    { builder: true, q: _ARR, target: "Tom is playing football.",              words: ["Tom", "is", "playing", "football."] },
    { builder: true, q: _ARR, target: "The dog is barking loudly.",            words: ["The", "dog", "is", "barking", "loudly."] },
    { builder: true, q: _ARR, target: "Ali went to school.",                   words: ["Ali", "went", "to", "school."] },
    { builder: true, q: _ARR, target: "She is reading a book.",                words: ["She", "is", "reading", "a book."] },
    { builder: true, q: _ARR, target: "Ben eats apples daily.",                words: ["Ben", "eats", "apples", "daily."] },
    { builder: true, q: _ARR, target: "The bird sings beautifully.",           words: ["The", "bird", "sings", "beautifully."] },
    { builder: true, q: _ARR, target: "Mother is cooking dinner.",             words: ["Mother", "is", "cooking", "dinner."] },
    { builder: true, q: _ARR, target: "The children are happy.",               words: ["The children", "are", "happy."] },
    { builder: true, q: _ARR, target: "I cleaned my room.",                    words: ["I", "cleaned", "my", "room."] },
    { builder: true, q: _ARR, target: "The cat is under the table.",           words: ["The", "cat", "is", "under", "the", "table."] },
    { builder: true, q: _ARR, target: "They are swimming now.",                words: ["They", "are", "swimming", "now."] },
    { builder: true, q: _ARR, target: "Sara baked a cake.",                    words: ["Sara", "baked", "a", "cake."] },
    { builder: true, q: _ARR, target: "The teacher is talking.",               words: ["The", "teacher", "is", "talking."] },
    { builder: true, q: _ARR, target: "The sun is shining brightly.",          words: ["The", "sun", "is", "shining", "brightly."] },
    { builder: true, q: _ARR, target: "He finished his homework.",             words: ["He", "finished", "his", "homework."] },
    { builder: true, q: _ARR, target: "The baby is crying.",                   words: ["The", "baby", "is", "crying."] },
    { builder: true, q: _ARR, target: "We went to the zoo.",                   words: ["We", "went", "to", "the", "zoo."] },
    { builder: true, q: _ARR, target: "The flowers are beautiful.",            words: ["The", "flowers", "are", "beautiful."] },
    { builder: true, q: _ARR, target: "He drinks milk every morning.",         words: ["He", "drinks", "milk", "every morning."] },
    { builder: true, q: _ARR, target: "My father is watching television.",     words: ["My", "father", "is", "watching", "television."] },
    { builder: true, q: _ARR, target: "John rides his bicycle.",               words: ["John", "rides", "his", "bicycle."] },
    { builder: true, q: _ARR, target: "The library is quiet.",                 words: ["The", "library", "is", "quiet."] },
    { builder: true, q: _ARR, target: "They are eating breakfast.",            words: ["They", "are", "eating", "breakfast."] },
    { builder: true, q: _ARR, target: "The puppy is sleeping.",                words: ["The", "puppy", "is", "sleeping."] },
    { builder: true, q: _ARR, target: "My friends play football.",             words: ["My", "friends", "play", "football."] },
    { builder: true, q: _ARR, target: "Mother washed the dishes.",             words: ["Mother", "washed", "the", "dishes."] },
    { builder: true, q: _ARR, target: "The children are laughing.",            words: ["The", "children", "are", "laughing."] },
    { builder: true, q: _ARR, target: "The cat is sitting on the chair.",      words: ["The", "cat", "is", "sitting", "on", "the", "chair."] },
    { builder: true, q: _ARR, target: "Students cleaned the classroom.",       words: ["Students", "cleaned", "the", "classroom."] },
    { builder: true, q: _ARR, target: "The monkey climbed the tree.",          words: ["The", "monkey", "climbed", "the", "tree."] },
    { builder: true, q: _ARR, target: "My aunt is preparing dinner.",          words: ["My", "aunt", "is", "preparing", "dinner."] },
    { builder: true, q: _ARR, target: "The rabbit ran quickly.",               words: ["The", "rabbit", "ran", "quickly."] },
    { builder: true, q: _ARR, target: "I like reading books.",                 words: ["I", "like", "reading", "books."] },
    { builder: true, q: _ARR, target: "The birds are singing.",                words: ["The", "birds", "are", "singing."] },
    { builder: true, q: _ARR, target: "The family went to the park.",          words: ["The", "family", "went", "to", "the", "park."] },
    { builder: true, q: _ARR, target: "He is drawing a picture.",              words: ["He", "is", "drawing", "a", "picture."] },
    { builder: true, q: _ARR, target: "The kitten drinks milk.",               words: ["The", "kitten", "drinks", "milk."] },
    { builder: true, q: _ARR, target: "The children played happily.",          words: ["The", "children", "played", "happily."] },
    { builder: true, q: _ARR, target: "Father is fixing my bicycle.",          words: ["Father", "is", "fixing", "my", "bicycle."] },
    { builder: true, q: _ARR, target: "Grandmother cooked breakfast.",         words: ["Grandmother", "cooked", "breakfast."] },
    { builder: true, q: _ARR, target: "The teacher is smiling.",               words: ["The", "teacher", "is", "smiling."] },
    { builder: true, q: _ARR, target: "The sky is blue.",                      words: ["The", "sky", "is", "blue."] },
    { builder: true, q: _ARR, target: "She finished her homework.",            words: ["She", "finished", "her", "homework."] },
    { builder: true, q: _ARR, target: "The girls are dancing.",                words: ["The", "girls", "are", "dancing."] },
    { builder: true, q: _ARR, target: "He opened the window.",                 words: ["He", "opened", "the", "window."] },
    { builder: true, q: _ARR, target: "The baby cried loudly.",                words: ["The", "baby", "cried", "loudly."] },
    { builder: true, q: _ARR, target: "We are watching a movie.",              words: ["We", "are", "watching", "a", "movie."] },
    { builder: true, q: _ARR, target: "My brother cleaned his shoes.",         words: ["My", "brother", "cleaned", "his", "shoes."] },
    { builder: true, q: _ARR, target: "The rainbow is beautiful.",             words: ["The", "rainbow", "is", "beautiful."] },
    /* ---- prefix / root-word MCQ (used to live in sentence_structure) ---- */
    { q: "Pick the correct prefix: \"It is ___ possible to fly without wings.\"", options: ["un", "im", "dis", "re"], answer: 1 },
    { q: "Pick the correct prefix for the opposite of \"happy\":", options: ["un", "im", "ir", "dis"], answer: 0 },
    { q: "Pick the correct prefix: \"Please ___ write your messy work.\" (do again)", options: ["re", "un", "dis", "mis"], answer: 0 },
    { q: "Pick the correct prefix for \"opposite of legal\":", options: ["im", "il", "ir", "in"], answer: 1 },
    { q: "Pick the correct prefix for \"opposite of regular\":", options: ["il", "im", "ir", "in"], answer: 2 },
    { q: "What is the root word of \"unkindly\"?", options: ["unkind", "kind", "kindly", "un"], answer: 1 },
    { q: "What is the root word of \"running\"?", options: ["runn", "run", "ning", "runni"], answer: 1 },
    { q: "What is the root word of \"careless\"?", options: ["car", "care", "less", "careles"], answer: 1 },
    { q: "What is the root word of \"misbehaving\"?", options: ["misbehave", "behave", "behaving", "mis"], answer: 1 },
    { q: "Add the prefix for 'opposite of patient':", options: ["un", "im", "ir", "il"], answer: 1 },
    { q: "Which sentence sounds natural (best)?", options: ["The clever fox tricked the farmers.", "The fox clever tricked farmers the.", "Tricked fox the clever farmers.", "Farmers the clever fox tricked the."], answer: 0 }
  ];


  /* ====================== GRAMMAR LOGIC (Gym) ====================== */
  const grammar_logic = [
    { q: "___ Preston and Tula in school today?", options: ["Is", "Are", "Was", "Am"], answer: 1 },
    { q: "The lion ___ caught in a hunter's net.", options: ["am", "are", "was", "is being"], answer: 2 },
    { q: "Drivers ___ surprised to see monkeys on the road yesterday.", options: ["is", "was", "were", "am"], answer: 2 },
    { q: "I ___ cleaning up my room now.", options: ["is", "are", "am", "be"], answer: 2 },
    { q: "\"Here ___ the birthday cake!\" said Mr Oldcastle.", options: ["is", "are", "am", "were"], answer: 0 },
    { q: "Teacher Jessica ___ silly with the colourful wig.", options: ["were", "are", "was", "am"], answer: 2 },
    { q: "The cats ___ sleeping on the sofa.", options: ["is", "are", "was", "am"], answer: 1 },
    { q: "There ___ one apple on the table.", options: ["are", "is", "were", "am"], answer: 1 },
    { q: "There ___ many books on the shelf.", options: ["is", "are", "was", "am"], answer: 1 },
    { q: "She ___ my best friend.", options: ["are", "is", "am", "were"], answer: 1 },
    { q: "We ___ at the park last Sunday.", options: ["was", "were", "is", "am"], answer: 1 },
    { q: "He ___ a brave boy.", options: ["are", "is", "am", "were"], answer: 1 },
    { q: "Choose the correct one: \"___ an apple\"", options: ["a", "an", "the a", "one a"], answer: 1 },
    { q: "Choose the correct one: \"___ umbrella\"", options: ["a", "an", "the an", "a an"], answer: 1 },
    { q: "Choose the correct one: \"___ dog barked.\"", options: ["An", "A", "Aan", "a an"], answer: 1 },
    { q: "Singular or plural? \"The boy ___ to school.\"", options: ["walk", "walks", "walking", "walken"], answer: 1 },
    { q: "Singular or plural? \"The boys ___ to school.\"", options: ["walks", "walk", "walking", "walken"], answer: 1 },
    { q: "One mouse, two ___ .", options: ["mouses", "mice", "mouse", "mices"], answer: 1 },
    { q: "One foot, two ___ .", options: ["foots", "feets", "feet", "foot"], answer: 2 },
    { q: "\"My friends ___ kind.\" Choose correctly.", options: ["is", "are", "was", "am"], answer: 1 },
    { q: "\"The dog ___ in the garden yesterday.\"", options: ["play", "plays", "played", "playing"], answer: 2 },
    { q: "\"She ___ a song now.\"", options: ["sing", "sings", "singing", "sang"], answer: 1 },
    { q: "Which is correct?", options: ["He don't like it.", "He doesn't like it.", "He not like it.", "He no like it."], answer: 1 },
    { q: "Which is correct?", options: ["They was happy.", "They were happy.", "They is happy.", "They am happy."], answer: 1 },
    { q: "\"___ you my friend?\"", options: ["Is", "Are", "Am", "Was"], answer: 1 },
    { q: "Choose: \"The lion's roar ___ loud.\"", options: ["are", "is", "am", "were"], answer: 1 },
    { q: "Which spelling is correct?", options: ["imposible", "impossible", "imposibble", "impossable"], answer: 1 },
    { q: "Which spelling is correct?", options: ["bicycle", "bicicle", "bisicle", "bycicle"], answer: 0 },
    { q: "Which spelling is correct?", options: ["cousin", "cusin", "cousine", "cuzin"], answer: 0 },
    { q: "Which spelling is correct?", options: ["subscibe", "subscribe", "superscribe", "subscrybe"], answer: 1 },
    /* ----- 50 added grammar-logic questions ----- */
    { q: "The boy ___ running fast.",                  options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "The cats ___ sleeping.",                     options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "She ___ happy yesterday.",                   options: ["were", "are", "was", "am"],  answer: 2 },
    { q: "They ___ playing football.",                 options: ["is", "was", "are", "am"],    answer: 2 },
    { q: "The bird ___ flying high.",                  options: ["is", "are", "were", "am"],   answer: 0 },
    { q: "We ___ at school yesterday.",                options: ["was", "is", "were", "am"],   answer: 2 },
    { q: "The monkey ___ climbing the tree.",          options: ["are", "is", "were", "am"],   answer: 1 },
    { q: "I ___ hungry this morning.",                 options: ["were", "was", "are", "is"],  answer: 1 },
    { q: "The children ___ noisy.",                    options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "My mother ___ cooking dinner.",              options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "The dogs ___ barking loudly.",               options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "He ___ tired yesterday.",                    options: ["are", "were", "was", "am"],  answer: 2 },
    { q: "The flowers ___ beautiful.",                 options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "They ___ late for school yesterday.",        options: ["was", "is", "were", "am"],   answer: 2 },
    { q: "The baby ___ crying loudly.",                options: ["are", "is", "were", "am"],   answer: 1 },
    { q: "My brothers ___ playing games.",             options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "She ___ at the library yesterday.",          options: ["were", "was", "are", "is"],  answer: 1 },
    { q: "The lion ___ sleeping.",                     options: ["are", "was", "is", "am"],    answer: 2 },
    { q: "We ___ excited about the trip.",             options: ["was", "were", "is", "am"],   answer: 1 },
    { q: "The teacher ___ talking to the class.",      options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "The cows ___ eating grass.",                 options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "My friend ___ absent yesterday.",            options: ["were", "was", "are", "am"],  answer: 1 },
    { q: "The books ___ on the table.",                options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "The dog ___ hungry yesterday.",              options: ["were", "was", "are", "is"],  answer: 1 },
    { q: "The students ___ studying quietly.",         options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "I ___ happy to see you.",                    options: ["are", "am", "were", "is"],   answer: 1 },
    { q: "The fish ___ swimming.",                     options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "They ___ at the zoo yesterday.",             options: ["was", "is", "were", "am"],   answer: 2 },
    { q: "The rabbit ___ jumping quickly.",            options: ["are", "is", "were", "am"],   answer: 1 },
    { q: "My father ___ washing the car.",             options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "The stars ___ shining brightly.",            options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "She ___ sleepy last night.",                 options: ["were", "was", "are", "am"],  answer: 1 },
    { q: "The teacher ___ kind.",                      options: ["are", "is", "were", "am"],   answer: 1 },
    { q: "The monkeys ___ eating bananas.",            options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "We ___ busy yesterday.",                     options: ["was", "were", "is", "am"],   answer: 1 },
    { q: "The cat ___ under the bed.",                 options: ["are", "is", "were", "am"],   answer: 1 },
    { q: "My sister ___ singing now.",                 options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "The boys ___ noisy yesterday.",              options: ["was", "were", "is", "am"],   answer: 1 },
    { q: "The bus ___ late this morning.",             options: ["were", "was", "are", "am"],  answer: 1 },
    { q: "The apples ___ fresh.",                      options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "The children ___ dancing happily.",          options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "The tiger ___ fierce.",                      options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "They ___ at home yesterday.",                options: ["was", "is", "were", "am"],   answer: 2 },
    { q: "My grandmother ___ baking cookies.",         options: ["are", "is", "were", "am"],   answer: 1 },
    { q: "The ducks ___ swimming in the pond.",        options: ["is", "are", "was", "am"],    answer: 1 },
    { q: "The girl ___ reading quietly.",              options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "We ___ hungry after school.",                options: ["was", "were", "is", "am"],   answer: 1 },
    { q: "The elephant ___ very big.",                 options: ["are", "were", "is", "am"],   answer: 2 },
    { q: "My shoes ___ dirty yesterday.",              options: ["was", "were", "is", "am"],   answer: 1 },
    { q: "The baby birds ___ hungry.",                 options: ["is", "are", "was", "am"],    answer: 1 }
  ];

  /* ====================== READING COMPREHENSION ====================== */
  const P_KIND = "A Kind Act\n\nAli and his younger sister, Mia, were playing at the park on a sunny afternoon. They were kicking a bright red ball and laughing together. Suddenly, Ali kicked the ball too hard, and it rolled quickly into a thick bush nearby. \"Oh no! Now we can't find it,\" Mia said. \"Don't worry, I'll get it,\" Ali replied. As he pushed the leaves aside, he heard a soft sound. \"Meow…\" It was a frightened kitten. \"We can't just leave it here,\" Mia said. \"Let's take it home and ask Mum for help.\" Together, they carried the kitten home, hoping to keep it safe.";
  const P_STORM = "The Night Storm\n\nLena could not sleep. The wind howled and rain hammered on her window. A bright flash of lightning lit up her room, and then a loud crash of thunder followed. She pulled her blanket over her head, but she was still afraid. Then she heard a gentle knock. It was her grandmother, holding a warm cup of milk. \"Storms are loud, but they cannot hurt you inside,\" Grandma said softly. Lena felt safe at last and soon fell asleep.";
  const P_FOX = "Fantastic Mr Fox\n\nBoggis was a chicken farmer. He was enormously fat because he ate three boiled chickens smothered in dumplings every day. Bunce was a duck and goose farmer. Bean was a turkey and apple farmer. But Mr Fox was too clever for them. He always approached a farm with the wind blowing in his face, so if any men were hiding in the shadows, the wind would carry their smell to his nose from far away.";
  const comprehension = [
    { passage: P_KIND, q: "What were Ali and Mia kicking?", options: ["a blue kite", "a bright red ball", "a small stone", "a green frisbee"], answer: 1 },
    { passage: P_KIND, q: "Where did the ball roll?", options: ["into the water", "into a thick bush", "down a hill", "onto the road"], answer: 1 },
    { passage: P_KIND, q: "How did Mia feel when the ball went missing?", options: ["Excited", "Angry", "Worried", "Sleepy"], answer: 2 },
    { passage: P_KIND, q: "What did Ali hear in the bush?", options: ["A bark", "A chirp", "A meow", "A roar"], answer: 2 },
    { passage: P_KIND, q: "What is this story mostly about?", options: ["children who argue about everything", "cats that can talk", "showing kindness to animals", "winning a football match"], answer: 2 },
    { passage: P_KIND, q: "When did Ali and Mia go to the park?", options: ["In the morning", "In the afternoon", "At night", "At midnight"], answer: 1 },
    { passage: P_KIND, q: "Why did Mia say they should take the kitten home?", options: ["To play with it", "To ask Mum for help", "To show their friends", "To sell it"], answer: 1 },
    { passage: P_KIND, q: "The word \"frightened\" means the kitten was:", options: ["happy", "scared", "hungry", "sleepy"], answer: 1 },
    { passage: P_KIND, q: "Who is older, Ali or Mia?", options: ["Mia", "Ali", "They are twins", "We are not told"], answer: 1 },
    { passage: P_STORM, q: "Why could Lena not sleep?", options: ["She was hungry", "There was a loud storm", "She was reading", "Her light was on"], answer: 1 },
    { passage: P_STORM, q: "What lit up her room?", options: ["A torch", "The moon", "Lightning", "A candle"], answer: 2 },
    { passage: P_STORM, q: "Who came to her room?", options: ["Her mother", "Her grandmother", "Her brother", "Her friend"], answer: 1 },
    { passage: P_STORM, q: "What did Grandma bring?", options: ["A blanket", "A book", "A warm cup of milk", "A torch"], answer: 2 },
    { passage: P_STORM, q: "How did Lena feel at the end?", options: ["Still afraid", "Angry", "Safe", "Excited"], answer: 2 },
    { passage: P_STORM, q: "The word \"howled\" tells us the wind was:", options: ["very quiet", "very loud", "warm", "gentle"], answer: 1 },
    { passage: P_FOX, q: "What kind of farmer was Boggis?", options: ["a duck farmer", "a chicken farmer", "a turkey farmer", "an apple farmer"], answer: 1 },
    { passage: P_FOX, q: "Why was Boggis enormously fat?", options: ["he never moved", "he ate three chickens every day", "he was born that way", "he ate sweets"], answer: 1 },
    { passage: P_FOX, q: "What did Bean farm?", options: ["ducks and geese", "chickens", "turkeys and apples", "cows"], answer: 2 },
    { passage: P_FOX, q: "Why did Mr Fox face the wind?", options: ["to feel cool", "to smell danger from far away", "to run faster", "to hear better"], answer: 1 },
    { passage: P_FOX, q: "The word \"clever\" means Mr Fox was:", options: ["slow", "smart", "lazy", "kind"], answer: 1 },
    { passage: P_FOX, q: "Who was a duck and goose farmer?", options: ["Boggis", "Bunce", "Bean", "Mr Fox"], answer: 1 }
  ];

  /* ============================ SPELLING (Study Room) ============================ */
  const spelling = [
    { q: "Which spelling is correct?", options: ["cousin", "cusin", "cousine", "cuzin"], answer: 0 },
    { q: "Which spelling is correct?", options: ["bicycle", "bicicle", "bisicle", "bycicle"], answer: 0 },
    { q: "Which spelling is correct?", options: ["impossible", "imposible", "imposibble", "impossable"], answer: 0 },
    { q: "Which spelling is correct?", options: ["subscribe", "subscibe", "superscribe", "subscrybe"], answer: 0 },
    { q: "Which spelling is correct?", options: ["anticlockwise", "anticlokwise", "antclockwise", "anticlokwize"], answer: 0 },
    { q: "Which spelling is correct?", options: ["imagination", "imagintion", "imaginasion", "imajination"], answer: 0 },
    { q: "Which spelling is correct?", options: ["young", "yong", "youngg", "yung"], answer: 0 },
    { q: "Which spelling is correct?", options: ["rewrite", "re-write", "rewite", "rewright"], answer: 0 },
    { q: "Which spelling is correct?", options: ["automatic", "automatik", "autometic", "atomatic"], answer: 0 },
    { q: "Which spelling is correct?", options: ["disappointed", "disapointed", "disapoiinted", "dissapointed"], answer: 0 },
    { q: "Which spelling is correct?", options: ["crystal", "krystal", "cristal", "crystle"], answer: 0 },
    { q: "Which spelling is correct?", options: ["impatient", "inpatient", "impatent", "impacient"], answer: 0 },
    { q: "Which spelling is correct?", options: ["illegal", "inlegal", "ilegal", "illeagle"], answer: 0 },
    { q: "Which spelling is correct?", options: ["rough", "ruff", "rugh", "rouf"], answer: 0 },
    { q: "Which spelling is correct?", options: ["enormous", "enormus", "enourmous", "enormos"], answer: 0 },
    { q: "Which spelling is correct?", options: ["beautiful", "beutiful", "beautifull", "beatiful"], answer: 0 },
    { q: "Which spelling is correct?", options: ["dangerous", "dangurous", "dangrous", "dangerus"], answer: 0 },
    { q: "Which spelling is correct?", options: ["carefully", "carefuly", "carefuilly", "carefuelly"], answer: 0 },
    { q: "Which spelling is correct?", options: ["surprise", "suprise", "surprize", "suprize"], answer: 0 },
    { q: "Which spelling is correct?", options: ["friend", "freind", "frend", "frinde"], answer: 0 },
    { q: "Which spelling is correct?", options: ["believe", "beleive", "belive", "beleve"], answer: 0 },
    { q: "Which spelling is correct?", options: ["because", "becuse", "becausse", "becouse"], answer: 0 },
    { q: "Which spelling is correct?", options: ["people", "peopel", "poeple", "peple"], answer: 0 },
    { q: "Which spelling is correct?", options: ["weather", "wether", "wheather", "waether"], answer: 0 },
    { q: "Which spelling is correct?", options: ["weight", "wieght", "waight", "weite"], answer: 0 },
    { q: "Which spelling is correct?", options: ["measure", "mesure", "meausre", "messure"], answer: 0 },
    { q: "Which spelling is correct?", options: ["minute", "minit", "minet", "minutte"], answer: 0 },
    { q: "Which spelling is correct?", options: ["island", "iland", "iseland", "ilan"], answer: 0 },
    { q: "Which spelling is correct?", options: ["answer", "ancer", "answr", "ansewr"], answer: 0 },
    { q: "Which spelling is correct?", options: ["different", "diferent", "differant", "difrent"], answer: 0 },
    { q: "Which spelling is correct?", options: ["favourite", "favorit", "favourit", "favorete"], answer: 0 },
    { q: "Which spelling is correct?", options: ["important", "importent", "impurtant", "imporant"], answer: 0 },
    { q: "Which spelling is correct?", options: ["library", "libary", "librery", "libreary"], answer: 0 },
    { q: "Which spelling is correct?", options: ["accident", "acident", "accidant", "axident"], answer: 0 },
    { q: "Which spelling is correct?", options: ["calendar", "calender", "calandar", "calenndar"], answer: 0 },
    { q: "Complete the sentence: \"I have a ___ sister called Sarah.\"", options: ["cousin", "cusin", "cousine", "cuzin"], answer: 0 },
    { q: "Complete the sentence: \"Klera likes the pretty ___ in her room.\"", options: ["crystal", "krystal", "cristal", "crystle"], answer: 0 },
    { q: "Complete the sentence: \"The footpath was very ___ and bumpy.\"", options: ["rough", "ruff", "rugh", "rouf"], answer: 0 },
    { q: "Complete the sentence: \"It is ___ to keep your eyes open while you sneeze.\"", options: ["impossible", "imposible", "imposibble", "impossable"], answer: 0 },
    { q: "Complete the sentence: \"Ashley ___ to a cooking channel.\"", options: ["subscribes", "subscibes", "subscrybes", "subsribes"], answer: 0 },
    { q: "Complete the sentence: \"I use my ___ to go to school every day.\"", options: ["bicycle", "bicicle", "bisicle", "bycicle"], answer: 0 },
    { q: "The opposite of \"happy\" (add the right prefix):", options: ["unhappy", "inhappy", "imhappy", "dishappy"], answer: 0 },
    { q: "The opposite of \"legal\" (add the right prefix):", options: ["illegal", "unlegal", "inlegal", "dislegal"], answer: 0 },
    { q: "The opposite of \"patient\" (add the right prefix):", options: ["impatient", "unpatient", "inpatient", "dispatient"], answer: 0 },
    { q: "The opposite of \"regular\" (add the right prefix):", options: ["irregular", "inregular", "unregular", "disregular"], answer: 0 },
    { q: "The opposite of \"responsible\" (add the right prefix):", options: ["irresponsible", "inresponsible", "unresponsible", "imresponsible"], answer: 0 },
    /* ---- added Year-3 spelling list (new words only) ---- */
    { q: "Which spelling is correct?", options: ["symbol", "cymbol", "symbal", "simbol"], answer: 0 },
    { q: "Which spelling is correct?", options: ["pyramid", "pyramide", "piramid", "pyramyd"], answer: 0 },
    { q: "Which spelling is correct?", options: ["touch", "tuch", "touche", "tutch"], answer: 0 },
    { q: "Which spelling is correct?", options: ["enough", "enuff", "enuf", "enought"], answer: 0 },
    { q: "Which spelling is correct?", options: ["syrup", "sirup", "syrop", "syrupp"], answer: 0 },
    { q: "Which spelling is correct?", options: ["incorrect", "incorect", "incorrekt", "uncorrect"], answer: 0 },
    { q: "Which spelling is correct?", options: ["international", "internasional", "interational", "internashional"], answer: 0 },
    { q: "Which spelling is correct?", options: ["subtract", "substract", "subtrack", "subtrct"], answer: 0 },
    { q: "Which spelling is correct?", options: ["supermarket", "supurmarket", "supermaket", "superrmarket"], answer: 0 },
    { q: "Which spelling is correct?", options: ["automobile", "automobil", "autombile", "automobeile"], answer: 0 },
    { q: "Which spelling is correct?", options: ["antisocial", "antisocail", "antisosial", "antesocial"], answer: 0 },
    { q: "Which spelling is correct?", options: ["antibiotics", "antibioticks", "antybiotics", "antibioticts"], answer: 0 },
    { q: "Which spelling is correct?", options: ["autograph", "autograf", "autogeraph", "otograph"], answer: 0 },
    { q: "Which spelling is correct?", options: ["determination", "determinetion", "deturmination", "deterimination"], answer: 0 },
    { q: "Which spelling is correct?", options: ["exploration", "exploretion", "eksploration", "exploaration"], answer: 0 },
    { q: "Which spelling is correct?", options: ["information", "informasion", "informtion", "informetion"], answer: 0 },
    { q: "Which spelling is correct?", options: ["angrily", "angerly", "angryly", "angarily"], answer: 0 },
    { q: "Which spelling is correct?", options: ["hungrily", "hungerly", "hungrylly", "hungarily"], answer: 0 },
    { q: "Which spelling is correct?", options: ["busily", "busly", "busilyy", "busally"], answer: 0 },
    { q: "Which spelling is correct?", options: ["easily", "easly", "easyly", "easaly"], answer: 0 }
  ];

  const QUESTIONS = { nouns, verbs, present_tense, pronouns, adjectives, punctuation, sentence_order, comprehension, spelling, grammar_logic };

  // Returns a clone of `q` with its options re-ordered randomly and the
  // `answer` index updated to still point at the correct option text. Builder
  // questions (word-rearrangement) are returned untouched.
  function shuffleQuestion(q) {
    if (!q || !q.options || q.builder) return q;
    const order = shuffle(q.options.map((_, i) => i));
    return Object.assign({}, q, {
      options: order.map(i => q.options[i]),
      answer:  order.indexOf(q.answer)
    });
  }

  // Per-mansion question overrides. When a mansion supplies its own bank for
  // a given topic, that bank is used instead of the default Year-3 bank.
  // Currently the Zombie Shopping Mall ships a Year-4 bank for 6 topics
  // (loaded by questions_mall.js as window.QUESTIONS_MALL).
  function bankFor(topic, mansionId) {
    if (mansionId === "zombie_mall" && window.QUESTIONS_MALL && Array.isArray(window.QUESTIONS_MALL[topic])) {
      return window.QUESTIONS_MALL[topic];
    }
    return QUESTIONS[topic];
  }

  // a fresh, shuffled, non-repeating pool for one battle — each question's
  // option order is randomised too, so the right answer isn't always "A".
  // mansionId (optional) routes some topics to a per-mansion bank.
  QUESTIONS.pool = function (topic, mansionId) {
    let all;
    if (topic === "mixed") {
      all = [];
      // Boss rooms mix every topic — include any per-mansion override so the
      // boss in the mall draws from Year-4 questions for the overridden topics.
      Object.keys(QUESTIONS).forEach(k => {
        if (!Array.isArray(QUESTIONS[k])) return;
        const bank = bankFor(k, mansionId) || QUESTIONS[k];
        all = all.concat(bank);
      });
    } else {
      all = bankFor(topic, mansionId) || nouns;
    }
    return shuffle(all).map(shuffleQuestion);
  };
  QUESTIONS.shuffle = shuffle;
  window.QUESTIONS = QUESTIONS;
})();
