/* questions_exam.js — Exam Preparation banks (drill mode, no monsters). */
(function () {
  "use strict";

  // Category codes:
  //   S = subject pronoun expected  (he, she, it, we, they, I, you)
  //   O = object pronoun expected   (him, her, us, them, me, you/it as object)
  //   C = sentence-choice — pick the whole grammatically correct sentence

  const y3s2_pronouns = [
    { q: "Adam is my brother. ___ is eight years old.", options: ["She", "He", "It", "They"], answer: 1, cat: "S" },
    { q: "Sarah is reading a book. ___ likes stories.", options: ["He", "She", "They", "It"], answer: 1, cat: "S" },
    { q: "The dog is sleeping. ___ is tired.", options: ["It", "We", "They", "Us"], answer: 0, cat: "S" },
    { q: "Ben and Tom are playing football. ___ are in the garden.", options: ["He", "It", "They", "She"], answer: 2, cat: "S" },
    { q: "Mia and I are classmates. ___ sit together.", options: ["They", "We", "Us", "She"], answer: 1, cat: "S" },
    { q: "Mum called Jake. She asked ___ to come home.", options: ["he", "him", "they", "we"], answer: 1, cat: "O" },
    { q: "I saw Anna at school. I waved to ___.", options: ["she", "her", "he", "they"], answer: 1, cat: "O" },
    { q: "The teacher gave Sam and me some books. She gave ___ three books.", options: ["we", "us", "they", "them"], answer: 1, cat: "O" },
    { q: "The boys were noisy. The teacher told ___ to be quiet.", options: ["they", "them", "he", "we"], answer: 1, cat: "O" },
    { q: "My father is a doctor. ___ works at a hospital.", options: ["He", "Him", "She", "It"], answer: 0, cat: "S" },
    { q: "Lucy is my cousin. I play with ___ every weekend.", options: ["she", "her", "they", "we"], answer: 1, cat: "O" },
    { q: "The children are hungry. ___ want some food.", options: ["Them", "They", "Him", "Us"], answer: 1, cat: "S" },
    { q: "My brother and I cleaned the room. Mum thanked ___.", options: ["we", "us", "they", "he"], answer: 1, cat: "O" },
    { q: "The cat is under the table. ___ is hiding.", options: ["It", "Them", "We", "Us"], answer: 0, cat: "S" },
    { q: "Mr Tan teaches English. ___ is very kind.", options: ["Her", "Them", "He", "Him"], answer: 2, cat: "S" },
    { q: "Kelly and Jane are sisters. ___ share a bedroom.", options: ["She", "Them", "They", "We"], answer: 2, cat: "S" },
    { q: "I am thirsty. Please give ___ some water.", options: ["I", "me", "we", "they"], answer: 1, cat: "O" },
    { q: "Dad bought a new bicycle. ___ is blue.", options: ["He", "It", "They", "Him"], answer: 1, cat: "S" },
    { q: "The teacher asked Amy a question. ___ answered correctly.", options: ["She", "Her", "Him", "Them"], answer: 0, cat: "S" },
    { q: "My friends invited ___ to their birthday party.", options: ["I", "me", "we", "they"], answer: 1, cat: "O" },
    { q: "Jack is very funny. ___ always makes us laugh.", options: ["He", "Him", "Her", "Them"], answer: 0, cat: "S" },
    { q: "I gave the book to Mary. I gave it to ___.", options: ["she", "her", "they", "we"], answer: 1, cat: "O" },
    { q: "The teacher called my friends. She asked ___ to come inside.", options: ["they", "them", "we", "he"], answer: 1, cat: "O" },
    { q: "My sister and I are hungry. ___ want to eat now.", options: ["Us", "We", "Them", "Her"], answer: 1, cat: "S" },
    { q: "The rabbit has long ears. ___ can jump very high.", options: ["They", "It", "We", "Them"], answer: 1, cat: "S" },
    { q: "Dad asked my brother to help. Dad called ___.", options: ["he", "him", "she", "they"], answer: 1, cat: "O" },
    { q: "Amy and Sue are at school. ___ are in Year 3.", options: ["They", "Them", "Her", "Us"], answer: 0, cat: "S" },
    { q: "I cannot carry this bag. Can you help ___?", options: ["I", "me", "we", "he"], answer: 1, cat: "O" },
    { q: "My grandparents are visiting us. ___ arrived this morning.", options: ["He", "Her", "They", "It"], answer: 2, cat: "S" },
    { q: "The teacher spoke to Ben and me. She spoke to ___.", options: ["we", "us", "they", "he"], answer: 1, cat: "O" }
,
    { q: "Jack likes swimming. ___ goes swimming every Saturday.", options: ["She", "Him", "He", "They"], answer: 2, cat: "S" },
    { q: "My sister is tired. ___ wants to sleep.", options: ["He", "She", "Her", "It"], answer: 1, cat: "S" },
    { q: "The bird is in the tree. ___ is singing.", options: ["It", "He", "She", "They"], answer: 0, cat: "S" },
    { q: "Sam and Joe are hungry. ___ want lunch.", options: ["Them", "We", "He", "They"], answer: 3, cat: "S" },
    { q: "Lily and I are going to the park. ___ will play on the swings.", options: ["We", "Us", "They", "I"], answer: 0, cat: "S" },
    { q: "Dad gave the ball to Tom. Dad gave it to ___.", options: ["he", "him", "her", "them"], answer: 1, cat: "O" },
    { q: "I saw Emily yesterday. I spoke to ___.", options: ["she", "her", "him", "them"], answer: 1, cat: "O" },
    { q: "Mum took my brother and me shopping. She took ___ to the mall.", options: ["we", "them", "us", "him"], answer: 2, cat: "O" },
    { q: "The puppies were hungry, so I fed ___.", options: ["them", "they", "us", "him"], answer: 0, cat: "O" },
    { q: "Please listen to ___. I have something to tell you.", options: ["I", "we", "me", "him"], answer: 2, cat: "O" },
    { q: "Peter is my best friend. ___ lives next door.", options: ["He", "She", "Him", "They"], answer: 0, cat: "S" },
    { q: "Jenny is good at drawing. ___ draws beautiful pictures.", options: ["She", "He", "Her", "It"], answer: 0, cat: "S" },
    { q: "The rabbit is white. ___ has long ears.", options: ["He", "She", "They", "It"], answer: 3, cat: "S" },
    { q: "Ali and Ravi are playing chess. ___ are having fun.", options: ["They", "Them", "We", "He"], answer: 0, cat: "S" },
    { q: "My brother and I are ready. ___ can leave now.", options: ["Us", "They", "I", "We"], answer: 3, cat: "S" },
    { q: "The teacher called Hannah. She wanted to speak to ___.", options: ["she", "her", "him", "them"], answer: 1, cat: "O" },
    { q: "Mum asked Dad to help. She called ___.", options: ["he", "her", "them", "him"], answer: 3, cat: "O" },
    { q: "The teacher gave my friends and me homework. She gave ___ five questions.", options: ["we", "us", "them", "him"], answer: 1, cat: "O" },
    { q: "I saw the children in the playground. I waved to ___.", options: ["them", "they", "us", "him"], answer: 0, cat: "O" },
    { q: "Can ___ help me carry this box?", options: ["him", "you", "her", "us"], answer: 1, cat: "S" },
    { q: "Daniel is my cousin. ___ lives in Kuala Lumpur.", options: ["He", "She", "Him", "They"], answer: 0, cat: "S" },
    { q: "My mother loves flowers. ___ has many plants in the garden.", options: ["She", "He", "Her", "It"], answer: 0, cat: "S" },
    { q: "The ball rolled under the chair. I picked ___ up.", options: ["it", "them", "him", "her"], answer: 0, cat: "O" },
    { q: "Sarah and Jane are dancing. ___ love music.", options: ["Them", "We", "He", "They"], answer: 3, cat: "S" },
    { q: "My father and I went fishing. ___ caught three fish.", options: ["Us", "They", "I", "We"], answer: 3, cat: "S" },
    { q: "Ben dropped his pencil. I picked it up for ___.", options: ["him", "he", "her", "them"], answer: 0, cat: "O" },
    { q: "Amy forgot her lunch. I shared my food with ___.", options: ["she", "her", "him", "them"], answer: 1, cat: "O" },
    { q: "Dad took my sister and me to the zoo. He bought ___ some ice cream.", options: ["we", "them", "us", "him"], answer: 2, cat: "O" },
    { q: "The kittens looked hungry. Mum gave ___ some milk.", options: ["they", "us", "him", "them"], answer: 3, cat: "O" },
    { q: "This present is for ___. Happy birthday!", options: ["him", "her", "you", "us"], answer: 2, cat: "O" }
,
    { q: "Which sentence is correct?", options: ["Him is my brother.", "He is my brother.", "Her is my brother.", "Them is my brother."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["She likes reading.", "Her likes reading.", "Him likes reading.", "Them likes reading."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["It is sleeping.", "Them is sleeping.", "Us is sleeping.", "Him are sleeping."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Them are playing football.", "They are playing football.", "Him are playing football.", "Us is playing football."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["We are classmates.", "Us are classmates.", "Them is classmates.", "Me are classmates."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mum gave the present to he.", "Mum gave the present to him.", "Mum gave the present to they.", "Mum gave the present to we."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["I spoke to she.", "I spoke to her.", "I spoke to he.", "I spoke to they."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Dad took we to school.", "Dad took us to school.", "Dad took they to school.", "Dad took he to school."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["The teacher praised they.", "The teacher praised them.", "The teacher praised we.", "The teacher praised he."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Me am hungry.", "I am hungry.", "Him am hungry.", "Them am hungry."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["She gave me a book.", "Her gave I a book.", "Him gave me a book.", "Them gave I a book."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["They helped us.", "Them helped we.", "Us helped they.", "Him helped we."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["We saw them at the park.", "Us saw they at the park.", "Them saw we at the park.", "Him saw us at the park."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["He gave her the pencil.", "Him gave she the pencil.", "Her gave he the pencil.", "Them gave she the pencil."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["They invited us to the party.", "Them invited we to the party.", "Us invited they to the party.", "Him invited we to the party."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Her is my sister.", "She is my sister.", "Him is my sister.", "Them is my sister."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["The teacher gave they some homework.", "The teacher gave them some homework.", "The teacher gave he some homework.", "The teacher gave we some homework."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Him plays football every Sunday.", "He plays football every Sunday.", "Them plays football every Sunday.", "Her play football every Sunday."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mum cooked dinner for we.", "Mum cooked dinner for us.", "Mum cooked dinner for they.", "Mum cooked dinner for he."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["They gave me a present.", "Them gave I a present.", "Us gave me a present.", "Him gave I a present."], answer: 0, cat: "C" }
  ];

  const y3s2_present_perfect = [
    { q: "I ___ watched this movie before.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "She ___ finished her homework.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "They ___ visited the zoo.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "He ___ eaten his lunch.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "We ___ played this game before.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "The cat ___ climbed onto the chair.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "I ___ lost my pencil.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "You ___ read this book before.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "My mum ___ cooked dinner.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "The birds ___ flown away.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "I ___ seen that dog before.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "She ___ written a letter.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "They ___ watched the match.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "He ___ broken his toy.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "We ___ been to the beach.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "The baby ___ slept for two hours.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "I ___ cleaned my room.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "You ___ done a good job.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "My brother ___ won a prize.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "The teacher ___ explained the lesson.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "I ___ baked a cake.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "She ___ lost her keys.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "They ___ finished their project.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "He ___ seen a lion at the zoo.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "We ___ fed the fish.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "The monkey ___ eaten the banana.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "I ___ posted the letter.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "You ___ missed the bus.", options: ["has", "have", "had", "having"], answer: 1, cat: "H" },
    { q: "My sister ___ drawn a picture.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "The rain ___ stopped.", options: ["has", "have", "had", "having"], answer: 0, cat: "H" },
    { q: "I __________ (watch) a very good movie.", options: ["has watched", "have watch", "has watch", "have watched"], answer: 3, cat: "P" },
    { q: "She __________ (finish) her homework already.", options: ["have finished", "has finish", "has finished", "have finish"], answer: 2, cat: "P" },
    { q: "They __________ (visit) the new library.", options: ["has visited", "have visited", "have visit", "has visit"], answer: 1, cat: "P" },
    { q: "He __________ (eat) all the cookies.", options: ["have eaten", "has eaten", "has eat", "have eat"], answer: 1, cat: "P" },
    { q: "We __________ (play) basketball this morning.", options: ["has played", "have played", "have play", "has play"], answer: 1, cat: "P" },
    { q: "The dog __________ (bark) at the cat.", options: ["has barked", "have barked", "has bark", "have bark"], answer: 0, cat: "P" },
    { q: "I __________ (lose) my ruler.", options: ["has lost", "have lose", "has lose", "have lost"], answer: 3, cat: "P" },
    { q: "You __________ (read) this story before.", options: ["has read", "have read", "have reading", "has reading"], answer: 1, cat: "P" },
    { q: "My mum __________ (cook) lunch for us.", options: ["have cooked", "has cook", "have cook", "has cooked"], answer: 3, cat: "P" },
    { q: "The birds __________ (fly) away.", options: ["has flown", "have flown", "have fly", "has fly"], answer: 1, cat: "P" },
    { q: "I __________ (see) that movie before.", options: ["has seen", "have see", "have seen", "has see"], answer: 2, cat: "P" },
    { q: "She __________ (write) an email to her friend.", options: ["have written", "has write", "has written", "have write"], answer: 2, cat: "P" },
    { q: "They __________ (watch) the fireworks.", options: ["has watched", "have watched", "have watch", "has watch"], answer: 1, cat: "P" },
    { q: "He __________ (break) his toy car.", options: ["has broken", "have broken", "has break", "have break"], answer: 0, cat: "P" },
    { q: "We __________ (be) to the science centre.", options: ["has been", "have be", "has be", "have been"], answer: 3, cat: "P" },
    { q: "The children __________ (eat) their ice cream.", options: ["has eaten", "have eaten", "have eat", "has eat"], answer: 1, cat: "P" },
    { q: "I __________ (clean) the classroom.", options: ["has cleaned", "have cleaned", "have clean", "has clean"], answer: 1, cat: "P" },
    { q: "You __________ (do) your homework.", options: ["has done", "have do", "have done", "has do"], answer: 2, cat: "P" },
    { q: "My brother __________ (win) the race.", options: ["have won", "has win", "has won", "have win"], answer: 2, cat: "P" },
    { q: "The teacher __________ (explain) the rule.", options: ["have explained", "has explain", "have explain", "has explained"], answer: 3, cat: "P" },
    { q: "I __________ (bake) some cookies.", options: ["has baked", "have baked", "have bake", "has bake"], answer: 1, cat: "P" },
    { q: "She __________ (lose) her pen.", options: ["has lost", "have lost", "has lose", "have lose"], answer: 0, cat: "P" },
    { q: "They __________ (finish) their homework.", options: ["has finished", "have finished", "have finish", "has finish"], answer: 1, cat: "P" },
    { q: "He __________ (see) a big snake.", options: ["have seen", "has see", "have see", "has seen"], answer: 3, cat: "P" },
    { q: "We __________ (feed) the chickens.", options: ["have fed", "has fed", "have feed", "has feed"], answer: 0, cat: "P" },
    { q: "I __________ (post) the letter.", options: ["has posted", "have posted", "have post", "has post"], answer: 1, cat: "P" },
    { q: "You __________ (miss) the bus.", options: ["has missed", "have missed", "have miss", "has miss"], answer: 1, cat: "P" },
    { q: "My sister __________ (draw) a cat.", options: ["have drawn", "has draw", "has drawn", "have draw"], answer: 2, cat: "P" },
    { q: "The rain __________ (stop).", options: ["have stopped", "has stop", "have stop", "has stopped"], answer: 3, cat: "P" },
    { q: "The baby __________ (sleep) for a long time.", options: ["have slept", "has slept", "has sleep", "have sleep"], answer: 1, cat: "P" },
    { q: "Which sentence is correct?", options: ["I have saw the new film.", "I have seen the new film.", "I has seen the new film.", "I have see the new film."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["She have finished her work.", "She has finished her work.", "She has finish her work.", "She have finish her work."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["They has visited the zoo.", "They have visited the zoo.", "They have visit the zoo.", "They has visit the zoo."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["He have eaten lunch.", "He has eaten lunch.", "He has ate lunch.", "He have ate lunch."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["We has played chess.", "We have played chess.", "We have play chess.", "We has play chess."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["It have rained heavily.", "It has rained heavily.", "It has rain heavily.", "It have rain heavily."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["You has done a good job.", "You have done a good job.", "You have did a good job.", "You has do a good job."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["My mum has cooked dinner.", "My mum have cooked dinner.", "My mum has cook dinner.", "My mum have cook dinner."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The cat have slept.", "The cat has slept.", "The cat has sleep.", "The cat have sleep."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["I have cleaned my room.", "I has cleaned my room.", "I have clean my room.", "I has clean my room."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["She has lost her bag.", "She have lost her bag.", "She has lose her bag.", "She have lose her bag."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["They have watched the movie.", "They has watched the movie.", "They have watch the movie.", "They has watch the movie."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["He has broken the window.", "He have broken the window.", "He has break the window.", "He have break the window."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["We have been to the beach.", "We has been to the beach.", "We have be to the beach.", "We has be to the beach."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["I have lost my keys.", "I has lost my keys.", "I have lose my keys.", "I has lose my keys."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["You have missed the class.", "You has missed the class.", "You have miss the class.", "You has miss the class."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["My brother has won the prize.", "My brother have won the prize.", "My brother has win the prize.", "My brother have win the prize."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The teacher has helped us.", "The teacher have helped us.", "The teacher has help us.", "The teacher have help us."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["I have posted the letter.", "I has posted the letter.", "I have post the letter.", "I has post the letter."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The babies have slept.", "The babies has slept.", "The babies have sleep.", "The babies has sleep."], answer: 0, cat: "C" }
  ];

  const y3s2_conjunctions = [
    { q: "I was hungry, ___ I made a sandwich.", options: ["but", "so", "or", "although"], answer: 1, cat: "CO" },
    { q: "Mia likes apples ___ oranges.", options: ["and", "because", "unless", "yet"], answer: 0, cat: "CO" },
    { q: "The bag is old, ___ it is still strong.", options: ["so", "but", "because", "when"], answer: 1, cat: "CO" },
    { q: "Would you like milk ___ juice?", options: ["and", "or", "so", "because"], answer: 1, cat: "CO" },
    { q: "I stayed inside ___ it was raining.", options: ["because", "but", "or", "until"], answer: 0, cat: "SU" },
    { q: "___ you finish your homework, you may watch TV.", options: ["If", "Yet", "Although", "Since"], answer: 0, cat: "SU" },
    { q: "I brushed my teeth ___ I went to bed.", options: ["before", "unless", "so", "yet"], answer: 0, cat: "SU" },
    { q: "We washed our hands ___ we ate lunch.", options: ["after", "before", "yet", "unless"], answer: 1, cat: "SU" },
    { q: "The baby smiled ___ Mum sang to her.", options: ["when", "or", "yet", "unless"], answer: 0, cat: "SU" },
    { q: "Dad cooked dinner ___ Mum set the table.", options: ["while", "because", "or", "unless"], answer: 0, cat: "SU" },
    { q: "Wait here ___ I come back.", options: ["until", "because", "although", "as"], answer: 0, cat: "SU" },
    { q: "___ it was cold, Ben went outside to play.", options: ["Although", "Because", "Until", "Or"], answer: 0, cat: "SU" },
    { q: "You cannot go swimming ___ an adult is with you.", options: ["unless", "and", "so", "after"], answer: 0, cat: "SU" },
    { q: "I packed my bag ___ I finished my homework.", options: ["after", "yet", "or", "although"], answer: 0, cat: "SU" },
    { q: "Sam was tired, ___ he finished the race.", options: ["yet", "because", "so", "until"], answer: 0, cat: "CO" },
    { q: "I wore a hat ___ the sun was very hot.", options: ["since", "or", "unless", "yet"], answer: 0, cat: "SU" },
    { q: "The dog barked ___ the doorbell rang.", options: ["when", "although", "or", "until"], answer: 0, cat: "SU" },
    { q: "We can play outside ___ stay indoors.", options: ["or", "because", "since", "while"], answer: 0, cat: "CO" },
    { q: "Amy cleaned her room ___ put away her toys.", options: ["and", "but", "unless", "although"], answer: 0, cat: "CO" },
    { q: "Tom wanted the toy, ___ he did not have enough money.", options: ["but", "so", "because", "after"], answer: 0, cat: "CO" },
    { q: "The floor was wet, ___ I walked carefully.", options: ["so", "or", "although", "unless"], answer: 0, cat: "CO" },
    { q: "___ Mum was cooking, I did my homework.", options: ["While", "Unless", "Yet", "Or"], answer: 0, cat: "SU" },
    { q: "We stayed at the park ___ it became dark.", options: ["until", "because", "although", "and"], answer: 0, cat: "SU" },
    { q: "___ you are tired, you should rest.", options: ["If", "Or", "Yet", "Before"], answer: 0, cat: "SU" },
    { q: "She was happy ___ she had won the game.", options: ["because", "but", "or", "unless"], answer: 0, cat: "SU" },
    { q: "___ the rain stopped, we went outside.", options: ["After", "Unless", "Yet", "Or"], answer: 0, cat: "SU" },
    { q: "I put on my shoes ___ leaving the house.", options: ["before", "although", "or", "since"], answer: 0, cat: "SU" },
    { q: "The kitten hid ___ it heard a loud noise.", options: ["as", "or", "yet", "unless"], answer: 0, cat: "SU" },
    { q: "He is small, ___ he is very brave.", options: ["yet", "because", "so", "until"], answer: 0, cat: "CO" },
    { q: "___ I was waiting for the bus, I read a book.", options: ["While", "Because", "Unless", "After"], answer: 0, cat: "SU" },
    { q: "The children laughed ___ played together.", options: ["before", "and", "until", "yet"], answer: 1, cat: "CO" },
    { q: "I wanted to go outside, ___ it started to rain.", options: ["if", "although", "while", "but"], answer: 3, cat: "CO" },
    { q: "The puppy was hungry, ___ I gave it some food.", options: ["so", "but", "or", "although"], answer: 0, cat: "CO" },
    { q: "Would you like to draw ___ read a book?", options: ["although", "until", "as", "or"], answer: 3, cat: "CO" },
    { q: "I wore my raincoat ___ it was raining.", options: ["when", "because", "or", "and"], answer: 1, cat: "SU" },
    { q: "___ you are ready, we can begin.", options: ["Since", "If", "So", "Although"], answer: 1, cat: "SU" },
    { q: "Wash your hands ___ you eat.", options: ["as", "because", "so", "before"], answer: 3, cat: "SU" },
    { q: "I went home ___ the football match ended.", options: ["if", "while", "so", "after"], answer: 3, cat: "SU" },
    { q: "I was sleeping ___ the phone rang.", options: ["when", "and", "if", "yet"], answer: 0, cat: "SU" },
    { q: "Mum read a book ___ Dad watched television.", options: ["because", "while", "unless", "since"], answer: 1, cat: "SU" },
    { q: "Stay here ___ your teacher comes back.", options: ["when", "until", "while", "but"], answer: 1, cat: "SU" },
    { q: "___ it was raining, the children continued playing.", options: ["But", "Although", "When", "Unless"], answer: 1, cat: "SU" },
    { q: "You cannot enter ___ you have a ticket.", options: ["yet", "unless", "after", "until"], answer: 1, cat: "SU" },
    { q: "I have known Sam ___ we were in Year 1.", options: ["unless", "since", "when", "until"], answer: 1, cat: "SU" },
    { q: "The bird flew away ___ the cat came closer.", options: ["since", "or", "until", "as"], answer: 3, cat: "SU" },
    { q: "The cake was small, ___ everyone had a piece.", options: ["since", "yet", "so", "or"], answer: 1, cat: "CO" },
    { q: "The classroom was quiet ___ the students were reading.", options: ["after", "when", "as", "because"], answer: 3, cat: "SU" },
    { q: "My sister can sing ___ dance.", options: ["and", "or", "after", "but"], answer: 0, cat: "CO" },
    { q: "I called Ben, ___ he did not answer.", options: ["while", "but", "so", "since"], answer: 1, cat: "CO" },
    { q: "It was getting late, ___ we went home.", options: ["so", "after", "although", "while"], answer: 0, cat: "CO" },
    { q: "You may choose the red pencil ___ the blue pencil.", options: ["or", "if", "and", "since"], answer: 0, cat: "CO" },
    { q: "___ you practise every day, you will improve.", options: ["So", "Although", "When", "If"], answer: 3, cat: "SU" },
    { q: "We packed our bags ___ we left for the airport.", options: ["after", "if", "before", "yet"], answer: 2, cat: "SU" },
    { q: "The children washed the dishes ___ they finished dinner.", options: ["although", "and", "after", "unless"], answer: 2, cat: "SU" },
    { q: "I smiled ___ I saw my birthday cake.", options: ["yet", "and", "because", "when"], answer: 3, cat: "SU" },
    { q: "The teacher wrote on the board ___ the class copied the notes.", options: ["while", "after", "before", "but"], answer: 0, cat: "SU" },
    { q: "The baby cried ___ Mum picked him up.", options: ["until", "or", "so", "while"], answer: 0, cat: "SU" },
    { q: "___ the book was difficult, Mia finished reading it.", options: ["Although", "Unless", "And", "Before"], answer: 0, cat: "SU" },
    { q: "I will not eat the cake ___ Mum says I can.", options: ["unless", "when", "while", "as"], answer: 0, cat: "SU" },
    { q: "Dad was pleased ___ I had cleaned my room.", options: ["unless", "yet", "when", "since"], answer: 3, cat: "SU" },
    { q: "Which sentence is correct?", options: ["I was tired, so I went to bed early.", "I was tired, or I went to bed early.", "I was tired, unless I went to bed early.", "I was tired, before I went to bed early."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mum bought bread because milk.", "Mum bought bread unless milk.", "Mum bought bread until milk.", "Mum bought bread and milk."], answer: 3, cat: "C" },
    { q: "Which sentence is correct?", options: ["The toy is old, or it still works.", "The toy is old, until it still works.", "The toy is old, but it still works.", "The toy is old, so it still works."], answer: 2, cat: "C" },
    { q: "Which sentence is correct?", options: ["Would you like tea although juice?", "Would you like tea or juice?", "Would you like tea because juice?", "Would you like tea until juice?"], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["I stayed home or I was sick.", "I stayed home yet I was sick.", "I stayed home before I was sick.", "I stayed home because I was sick."], answer: 3, cat: "C" },
    { q: "Which sentence is correct?", options: ["Or it rains, we will stay inside.", "Until it rains, we will stay inside.", "If it rains, we will stay inside.", "Yet it rains, we will stay inside."], answer: 2, cat: "C" },
    { q: "Which sentence is correct?", options: ["I packed my bag before I left home.", "I packed my bag unless I left home.", "I packed my bag yet I left home.", "I packed my bag or I left home."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Or I finished dinner, I washed my plate.", "After I finished dinner, I washed my plate.", "Unless I finished dinner, I washed my plate.", "Yet I finished dinner, I washed my plate."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["I smiled or I saw my friend.", "I smiled yet I saw my friend.", "I smiled when I saw my friend.", "I smiled unless I saw my friend."], answer: 2, cat: "C" },
    { q: "Which sentence is correct?", options: ["I read a book unless Mum cooked dinner.", "I read a book or Mum cooked dinner.", "I read a book until Mum cooked dinner.", "I read a book while Mum cooked dinner."], answer: 3, cat: "C" },
    { q: "Which sentence is correct?", options: ["Wait here or I return.", "Wait here until I return.", "Wait here because I return.", "Wait here but I return."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["Although it was cold, we went for a walk.", "Because it was cold, but we went for a walk.", "Until it was cold, we went for a walk.", "Or it was cold, we went for a walk."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["You cannot play outside yet you finish your homework.", "You cannot play outside until you do not finish your homework.", "You cannot play outside unless you finish your homework.", "You cannot play outside and you finish your homework."], answer: 2, cat: "C" },
    { q: "Which sentence is correct?", options: ["I have lived here or I was five.", "I have lived here but I was five.", "I have lived here until I was five.", "I have lived here since I was five."], answer: 3, cat: "C" },
    { q: "Which sentence is correct?", options: ["The children became quiet yet the teacher entered.", "The children became quiet as the teacher entered.", "The children became quiet or the teacher entered.", "The children became quiet unless the teacher entered."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["The bag is heavy, yet Mia can carry it.", "The bag is heavy, so Mia cannot carry it.", "The bag is heavy, until Mia can carry it.", "The bag is heavy, or Mia can carry it."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Ben washed the car unless cleaned the windows.", "Ben washed the car because cleaned the windows.", "Ben washed the car until cleaned the windows.", "Ben washed the car and cleaned the windows."], answer: 3, cat: "C" },
    { q: "Which sentence is correct?", options: ["The road was busy, unless we crossed carefully.", "The road was busy, although we crossed carefully.", "The road was busy, so we crossed carefully.", "The road was busy, or we crossed carefully."], answer: 2, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mia wanted to play, or she had homework to finish.", "Mia wanted to play, but she had homework to finish.", "Mia wanted to play, so she had homework to finish.", "Mia wanted to play, until she had homework to finish."], answer: 1, cat: "C" },
    { q: "Which sentence is correct?", options: ["You can have an apple or a banana.", "You can have an apple because a banana.", "You can have an apple until a banana.", "You can have an apple although a banana."], answer: 0, cat: "C" }
  ];

  const y3s2_prepositions = [
    { q: "The cat is hiding ___ the table.", options: ["under", "during", "until", "before"], answer: 0, cat: "PL" },
    { q: "We have our English lesson ___ Monday.", options: ["at", "on", "inside", "through"], answer: 1, cat: "TI" },
    { q: "The aeroplane is flying ___ the clouds.", options: ["above", "after", "during", "until"], answer: 0, cat: "PL" },
    { q: "Mia stood ___ her mother in the queue.", options: ["beside", "before", "around", "during"], answer: 0, cat: "PL" },
    { q: "The children walked ___ the bridge to reach the park.", options: ["across", "until", "after", "at"], answer: 0, cat: "PL" },
    { q: "The dog ran ___ the open gate.", options: ["through", "during", "before", "on"], answer: 0, cat: "PL" },
    { q: "The books are ___ the school bag.", options: ["inside", "during", "after", "around"], answer: 0, cat: "PL" },
    { q: "The boy ran ___ the stairs to his bedroom.", options: ["up", "before", "during", "among"], answer: 0, cat: "PL" },
    { q: "Dad walked ___ the bakery without going in.", options: ["past", "until", "inside", "at"], answer: 0, cat: "PL" },
    { q: "The teacher walked ___ the rows of desks.", options: ["along", "after", "during", "on"], answer: 0, cat: "PL" },
    { q: "The ball rolled ___ the chair.", options: ["behind", "during", "before", "at"], answer: 0, cat: "PL" },
    { q: "The picture is hanging ___ the sofa.", options: ["above", "after", "until", "around"], answer: 0, cat: "PL" },
    { q: "The rabbit sat ___ the flowers.", options: ["among", "during", "before", "at"], answer: 0, cat: "PL" },
    { q: "We travelled ___ the escalator to the ground floor.", options: ["down", "during", "after", "on"], answer: 0, cat: "PL" },
    { q: "The children are waiting ___ the bus stop.", options: ["at", "through", "behind", "during"], answer: 0, cat: "PL" },
    { q: "The pencil is ___ the desk.", options: ["on", "until", "during", "after"], answer: 0, cat: "PL" },
    { q: "We stayed indoors ___ the storm.", options: ["during", "above", "across", "beside"], answer: 0, cat: "TI" },
    { q: "Please wash your hands ___ dinner.", options: ["before", "under", "inside", "across"], answer: 0, cat: "TI" },
    { q: "We played football ___ lunch.", options: ["after", "above", "among", "through"], answer: 0, cat: "TI" },
    { q: "I read my book ___ bedtime.", options: ["until", "under", "beside", "over"], answer: 0, cat: "TI" },
    { q: "The show starts ___ seven o'clock.", options: ["at", "behind", "during", "along"], answer: 0, cat: "TI" },
    { q: "My family goes swimming ___ Saturdays.", options: ["on", "through", "inside", "past"], answer: 0, cat: "PL" },
    { q: "I usually eat lunch ___ noon.", options: ["around", "under", "over", "through"], answer: 0, cat: "TI" },
    { q: "The bell rang ___ we were leaving the classroom.", options: ["as", "inside", "above", "past"], answer: 0, cat: "PL" },
    { q: "Ella packed her bag ___ going to school.", options: ["before", "through", "over", "beside"], answer: 0, cat: "TI" },
    { q: "The children had ice cream ___ the movie.", options: ["after", "inside", "down", "among"], answer: 0, cat: "TI" },
    { q: "We stayed at the beach ___ sunset.", options: ["until", "across", "behind", "above"], answer: 0, cat: "TI" },
    { q: "The baby slept ___ the afternoon.", options: ["during", "on", "beside", "through"], answer: 0, cat: "TI" },
    { q: "The bus arrived ___ eight o'clock.", options: ["at", "inside", "past", "over"], answer: 0, cat: "TI" },
    { q: "We visit Grandma ___ Sundays.", options: ["on", "among", "behind", "during"], answer: 0, cat: "PL" },
    { q: "The shoes are ___ the bed.", options: ["past", "before", "at", "under"], answer: 3, cat: "PL" },
    { q: "My lunchbox is ___ my school bag.", options: ["inside", "of", "after", "around"], answer: 0, cat: "PL" },
    { q: "The teacher is standing ___ the whiteboard.", options: ["among", "on", "beside", "under"], answer: 2, cat: "PL" },
    { q: "A bird is flying ___ the house.", options: ["after", "through", "inside", "above"], answer: 3, cat: "PL" },
    { q: "The children ran ___ the field.", options: ["as", "across", "with", "in"], answer: 1, cat: "PL" },
    { q: "We walked ___ the tunnel.", options: ["under", "up", "through", "past"], answer: 2, cat: "PL" },
    { q: "The car drove ___ the school without stopping.", options: ["after", "past", "from", "with"], answer: 1, cat: "PL" },
    { q: "The hikers walked ___ the river.", options: ["during", "along", "on", "from"], answer: 1, cat: "PL" },
    { q: "The puppy is hiding ___ the door.", options: ["behind", "past", "across", "among"], answer: 0, cat: "PL" },
    { q: "The girl walked ___ the steps carefully.", options: ["down", "among", "from", "over"], answer: 0, cat: "PL" },
    { q: "The boy climbed ___ the ladder.", options: ["past", "as", "behind", "up"], answer: 3, cat: "PL" },
    { q: "The crayons are ___ the table.", options: ["past", "down", "in", "on"], answer: 3, cat: "PL" },
    { q: "We are waiting ___ the airport.", options: ["at", "after", "behind", "through"], answer: 0, cat: "PL" },
    { q: "The red apple is ___ the green apples.", options: ["among", "down", "with", "along"], answer: 0, cat: "PL" },
    { q: "The plane flew ___ the sea.", options: ["before", "over", "on", "until"], answer: 1, cat: "PL" },
    { q: "I brush my teeth ___ I go to bed.", options: ["before", "during", "across", "on"], answer: 0, cat: "TI" },
    { q: "We ate dessert ___ dinner.", options: ["over", "along", "after", "with"], answer: 2, cat: "TI" },
    { q: "The students were quiet ___ the test.", options: ["during", "from", "down", "over"], answer: 0, cat: "TI" },
    { q: "I waited ___ Mum came home.", options: ["until", "above", "over", "along"], answer: 0, cat: "TI" },
    { q: "The clock struck twelve ___ we cheered.", options: ["along", "as", "around", "among"], answer: 1, cat: "PL" },
    { q: "My music lesson is ___ Thursday.", options: ["in", "among", "up", "on"], answer: 3, cat: "TI" },
    { q: "The party begins ___ three o'clock.", options: ["beside", "over", "through", "at"], answer: 3, cat: "TI" },
    { q: "We usually have lunch ___ noon.", options: ["past", "above", "around", "as"], answer: 2, cat: "TI" },
    { q: "Sam finished his homework ___ watching television.", options: ["before", "of", "under", "inside"], answer: 0, cat: "TI" },
    { q: "The family went for a walk ___ breakfast.", options: ["after", "under", "above", "during"], answer: 0, cat: "TI" },
    { q: "The baby cried ___ the night.", options: ["down", "at", "during", "through"], answer: 2, cat: "TI" },
    { q: "We stayed in the library ___ it was time to go home.", options: ["beside", "before", "until", "with"], answer: 2, cat: "TI" },
    { q: "The lights came on ___ the sun went down.", options: ["as", "up", "with", "on"], answer: 0, cat: "PL" },
    { q: "Our sports day is ___ Friday.", options: ["on", "through", "of", "from"], answer: 0, cat: "TI" },
    { q: "Dad gets home ___ six o'clock.", options: ["as", "around", "on", "up"], answer: 1, cat: "TI" },
    { q: "Which sentence is correct?", options: ["The cat is under the chair.", "The cat is during the chair.", "The cat is until the chair.", "The cat is before the chair."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["We have PE on Tuesday.", "We have PE at Tuesday.", "We have PE under Tuesday.", "We have PE through Tuesday."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The bird flew above the trees.", "The bird flew during the trees.", "The bird flew after the trees.", "The bird flew until the trees."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Lina stood beside her sister.", "Lina stood during her sister.", "Lina stood until her sister.", "Lina stood after her sister."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The children ran across the playground.", "The children ran during the playground.", "The children ran before the playground.", "The children ran at the playground across."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The train went through the tunnel.", "The train went until the tunnel.", "The train went after the tunnel through.", "The train went during the tunnel."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The toys are inside the box.", "The toys are during the box.", "The toys are after the box.", "The toys are until the box."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["Mum walked past the shop.", "Mum walked during the shop.", "Mum walked at the shop past.", "Mum walked until the shop."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The boy climbed up the stairs.", "The boy climbed during the stairs.", "The boy climbed after the stairs.", "The boy climbed until the stairs."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The puppy is behind the sofa.", "The puppy is during the sofa.", "The puppy is after the sofa.", "The puppy is until the sofa."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["I wash my hands before dinner.", "I wash my hands above dinner.", "I wash my hands behind dinner.", "I wash my hands through dinner."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["We played in the park after lunch.", "We played in the park under lunch.", "We played in the park inside lunch.", "We played in the park across lunch."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The baby slept during the afternoon.", "The baby slept beside the afternoon.", "The baby slept over the afternoon.", "The baby slept behind the afternoon."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["I waited until the rain stopped.", "I waited above the rain stopped.", "I waited beside the rain stopped.", "I waited across the rain stopped."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["School starts at eight o'clock.", "School starts on eight o'clock.", "School starts inside eight o'clock.", "School starts through eight o'clock."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["We visit Grandma on Sunday.", "We visit Grandma at Sunday.", "We visit Grandma behind Sunday.", "We visit Grandma through Sunday."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["I usually eat lunch around noon.", "I usually eat lunch under noon.", "I usually eat lunch beside noon.", "I usually eat lunch across noon."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The bell rang as we left the room.", "The bell rang under we left the room.", "The bell rang inside we left the room.", "The bell rang above we left the room."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The plane flew over the sea.", "The plane flew during the sea.", "The plane flew before the sea.", "The plane flew until the sea."], answer: 0, cat: "C" },
    { q: "Which sentence is correct?", options: ["The rabbit sat among the flowers.", "The rabbit sat during the flowers.", "The rabbit sat before the flowers.", "The rabbit sat until the flowers."], answer: 0, cat: "C" }
  ];

  window.QUESTIONS_EXAM = { y3s2_pronouns, y3s2_present_perfect, y3s2_conjunctions, y3s2_prepositions };
})();